### ISSUE TITLE
Dashboard NFS page returns 500

### ISSUE THREAD

**Issue by mecseid** [rook/rook#11096]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I got an HTTP 200 with error message when the dashboard wants to call `/ui-api/nfs-ganesha/status`.
I think this issue is related to https://github.com/rook/rook/issues/10995.

**Expected behavior:**
Show NFS page without any error.

**How to reproduce it (minimal and precise):**

* Create a CephNFS custom resource
* Open dashboard
* Enable `nfs` mgr module
* Go to NFS page

**File(s) to submit**:
CephNFS CR:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephNFS
metadata:
  name: nfs
  namespace: rook-ceph
spec:
  server:
    active: 1
    logLevel: NIV_INFO
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
```

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* mgr logs
```
debug 2022-10-03T12:14:58.885+0000 7efd99967700  0 [rook INFO rook.rook_cluster] Full fetch of <bound method CustomObjectsApi.list_namespaced_custom_object of <kubernetes.client.api.custom_objects_api.CustomObjectsApi object at 0x7efdc02079e8>>. result: 1
debug 2022-10-03T12:14:58.894+0000 7efd99967700  0 [rook ERROR orchestrator._interface] 'pool'
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 125, in wrapper
    return OrchResult(f(*args, **kwargs))
  File "/usr/share/ceph/mgr/rook/module.py", line 354, in describe_service
    if nfs['spec']['rados']['pool'] != NFS_POOL_NAME:
KeyError: 'pool'
debug 2022-10-03T12:14:58.896+0000 7efd99967700 -1 Remote method threw exception: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/nfs/module.py", line 154, in cluster_ls
    return available_clusters(self)
  File "/usr/share/ceph/mgr/nfs/utils.py", line 39, in available_clusters
    orchestrator.raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
    raise e
KeyError: 'pool'

debug 2022-10-03T12:14:58.897+0000 7efd99967700  0 [dashboard ERROR controllers.nfs] Remote method threw exception: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/nfs/module.py", line 154, in cluster_ls
    return available_clusters(self)
  File "/usr/share/ceph/mgr/nfs/utils.py", line 39, in available_clusters
    orchestrator.raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
    raise e
KeyError: 'pool'
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/controllers/nfs.py", line 271, in status
    mgr.remote('nfs', 'cluster_ls')
  File "/usr/share/ceph/mgr/mgr_module.py", line 2170, in remote
    args, kwargs)
RuntimeError: Remote method threw exception: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/nfs/module.py", line 154, in cluster_ls
    return available_clusters(self)
  File "/usr/share/ceph/mgr/nfs/utils.py", line 39, in available_clusters
    orchestrator.raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
    raise e
KeyError: 'pool'

debug 2022-10-03T12:14:58.901+0000 7efd99967700  0 [dashboard INFO request] [10.142.133.1:41510] [GET] [200] [0.079s] [admin] [264.0B] /ui-api/nfs-ganesha/status
```

**Environment**:

* Rook version (use rook version inside of a Rook Pod): v1.10.2
* Storage backend version (e.g. for ceph do ceph -v): ceph version 17.2.4 (1353ed37dec8d74973edc3d5d5908c20ad5a7332) quincy (stable)
* Kubernetes version (use kubectl version): v1.24.4

**Comment by travisn** [comment]
This looks specific to the nfs mgr module, but @jmolmo thanks for taking the first look

**Comment by jmolmo** [comment]
@Travis, @mecseid : 
I think this is the bug [55605](https://tracker.ceph.com/issues/55605) solved in pr [#46321 ](https://github.com/ceph/ceph/pull/46321)

I think it was [backported](https://tracker.ceph.com/issues/57601) to Quincy only 12 days ago... 

@mecseid could it be that your cluster was installed previously? If your cluster is new i will try to reproduce. :-)

**Comment by mecseid** [comment]
@jmolmo As I saw from https://github.com/ceph/ceph/blob/v17.2.4/src/pybind/mgr/rook/module.py#L353, the v17.2.4 release doesn't contain the mentioned PR. :(

**Comment by jmolmo** [comment]
@mecseid : If you are interested in fix the problem in your cluster, you will need to upgrade to a Ceph version including the change:
I have seen that you have a Quincy version v17.2.4-20220930 that must include the fix, (it was merged on 20220923).

So upgrade your cluster CRD with:
    image: quay.io/ceph/ceph:v17.2.4-20220930
    
Note: Follow [upgrade documentation](https://rook.io/docs/rook/v1.10/Upgrade/ceph-upgrade/)

**Comment by mecseid** [comment]
@jmolmo Yes, I thought too that `v17.2.4-20220930` will contain the fix, but it not. I already upgraded to the mentioned version, but the problem still exists, and as I saw in GitHub, the v17.2.4 doesn't contain the modification.

Running pods:
```sh
$ kubectl get pods -n rook-ceph --output custom-columns="POD_NAME:metadata.name,IMAGE:spec.containers[*].image"
POD_NAME                                             IMAGE
csi-cephfsplugin-26c2l                               registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-cephfsplugin-72cnh                               registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-cephfsplugin-7mr9m                               registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-cephfsplugin-cxf6l                               registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-cephfsplugin-ddfwr                               registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-cephfsplugin-hj8z6                               registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-cephfsplugin-provisioner-cfcc76d97-5npff         registry.k8s.io/sig-storage/csi-attacher:v3.5.0,registry.k8s.io/sig-storage/csi-resizer:v1.5.0,registry.k8s.io/sig-storage/csi-provisioner:v3.2.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-cephfsplugin-provisioner-cfcc76d97-rm94w         registry.k8s.io/sig-storage/csi-attacher:v3.5.0,registry.k8s.io/sig-storage/csi-resizer:v1.5.0,registry.k8s.io/sig-storage/csi-provisioner:v3.2.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-cephfsplugin-qw8xs                               registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-cephfsplugin-xfrzp                               registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-rbdplugin-bfwtx                                  registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-rbdplugin-fbrwz                                  registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-rbdplugin-kjlvb                                  registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-rbdplugin-provisioner-bb9bdfb64-gxzrb            registry.k8s.io/sig-storage/csi-provisioner:v3.2.1,registry.k8s.io/sig-storage/csi-resizer:v1.5.0,registry.k8s.io/sig-storage/csi-attacher:v3.5.0,quay.io/cephcsi/cephcsi:v3.7.0
csi-rbdplugin-provisioner-bb9bdfb64-t95ss            registry.k8s.io/sig-storage/csi-provisioner:v3.2.1,registry.k8s.io/sig-storage/csi-resizer:v1.5.0,registry.k8s.io/sig-storage/csi-attacher:v3.5.0,quay.io/cephcsi/cephcsi:v3.7.0
csi-rbdplugin-rstk7                                  registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-rbdplugin-rtrbf                                  registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-rbdplugin-wxs2v                                  registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-rbdplugin-x7gxd                                  registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
csi-rbdplugin-zxflf                                  registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1,quay.io/cephcsi/cephcsi:v3.7.0
rook-ceph-mds-replica-fs-mirror-a-69bdb56546-nptdp   quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-mds-replica-fs-mirror-b-7965976c4-ts5jj    quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-mgr-a-6c696f9868-4lnt7                     quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-mon-d-74d648b6d4-sh4wc                     quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-mon-e-55fc48b6c5-sww9l                     quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-mon-f-847d446dd4-r949c                     quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-nfs-nfs-a-74d8d57f86-pfzn6                 quay.io/ceph/ceph:v17.2.4-20220930,quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-operator-547768554f-56rln                  rook/ceph:v1.10.2
rook-ceph-osd-3-7b5777d5ff-4gwx6                     quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-osd-5-76bdbd89d5-jqzdt                     quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-osd-6-9bb4867b4-zckbj                      quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-osd-prepare-k8s-storage-1-gfhxg            quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-osd-prepare-k8s-storage-2-lgw8z            quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-osd-prepare-k8s-storage-3-d9mjz            quay.io/ceph/ceph:v17.2.4-20220930
rook-ceph-tools-79bc54b8d8-tx9zf                     quay.io/ceph/ceph:v17.2.3
```

**Comment by travisn** [comment]
If you need to test the fix that didn't make it into 17.2.4, there is a daily image build for everything that is merged to the quincy branch: `quay.io/ceph/daemon-base:latest-quincy-devel`. It's not technically supported since it's not an official release, but at least it's there for testing.

**Comment by mecseid** [comment]
Cool, thank you so much @jmolmo and @travisn .
Because it's not an official release, I will wait for the next bugfix version. :)

**Comment by jmolmo** [comment]
Duplicate of https://github.com/rook/rook/issues/10995
