### ISSUE TITLE
Document switching host network setting for the rook-ceph cluster

### ISSUE THREAD

**Issue by zxl716** [rook/rook#11748]
Hello, the rook-ceph cluster is running, how to modify the host network mode without affecting the business

**Comment by zhucan** [comment]
I remember no way to modify the host network online, only can rebuild the cluster.

**Comment by travisn** [comment]
If you are running Rook v1.10.5 or newer (since #11211 was fixed), you should be able to convert to and from host network settings. After you change the host network setting, then you will need to [failover the mons](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-mon-health/#failing-over-a-monitor). Please do try this first on a test cluster before a production cluster.

**Comment by zxl716** [comment]
@travisn Thank you for your answer, do you have specific steps?

**Comment by zxl716** [comment]
@zhucan Yes, the Rook v1.10 series documentation prompts "Changing this setting is not supported in a running Rook cluster. Host networking should be configured when the cluster is first created."

**Comment by travisn** [comment]
That comment in the documentation is outdated, we need to remove that now since the fix in #11211. The procedure I would expect is:
1. Deploy the cluster with the default settings (without host networking)
2. Decide that you want to enable host networking
3. Update the CephCluster CR to enable host networking: `provider: host`
4. Wait for the cluster to settle. Most of the daemons will likely restart that will turn on the host networking. The mons are not expected to restart since they will retain their non-host network settings.
5. Now [failover the mons](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-mon-health/#failing-over-a-monitor). When this is completed all the mons will be running on host networking along with all other daemons. 

I recommend trying this first in a test cluster to confirm if there is any disruption during any of these steps.

**Comment by zxl716** [comment]
@travisn Thank you for your reply, I followed the steps you said, but it still doesn't work. I rebuild the cluster

**Comment by travisn** [comment]
@zxl716 Do you have more details on which step failed and what was the issue? It would be good to get this scenario working if we can.

**Comment by zxl716** [comment]
@travisn Thank you for your reply; after switching the host network, osd mgr mds is the host network mode. But mon is not a host networking mode. What adjustments are needed for external use?

**Comment by zeddit** [comment]
I have exactly followed @travisn 's guide and successfully turned a running cluster to the `host networking` mode.
Some more information that may be useful to later people.
1. we only need to switch the `network.provider:host` in cluster.yaml to turn on host networking mode, configurations about host networking in operator.yaml are not necessary.
2. travisn said that Most of the daemons will restart. As I noticed, mgr, mds, osd daemons are restart sequentially (I haven't deployed obj rgw instance), and they switched to host networking mode. besides, rbd, cephfs node csi plugin which provide the access to the underlying storage also switched to host networking mode.
3. we could use `kubectl get po -nrook-ceph` to see if and which pod is in host networking mode, i.e. it will have an IP of host machines instead overlay IP inside k8s cluster like 10.42.x.x
4. mons won't switch to host networking mode automatically, we need to fail over it manually. the method I used is `kubectl scale deployment rook-ceph-mon-a --replicas=0 -nrook-ceph`. it will shutdown one of the mons and the rook operator will start a new one e.g. rook-ceph-mon-d when the internal timer timeout, the default one is about 10m, we can turn down it for fast rotation. we need to fail over the mons one by one, that is to say, until the operator start a replaced mon and the cluster run back into steady states, we should not start failing over the next mon.
5. [trouble shooting] people may find the cephfs still cannot be accessed from outside the k8s cluster. One of the reasons may be the mds server restarts not correctly. My problem is that I found even though the mds-a pod shows it is in host networking mode, the ceph cluster still record its position with the original internal overlay IP address, thus machine outside the k8s cluster cannot reach the mds. the solution is failover the mds pod with `kubectl scale deployment rook-ceph-mds-rook-fs-a --replicas=0 -nrook-ceph` and scale back. The mds will get its host IP and then can be reached from outside.

**Comment by zxl716** [comment]
@ze
Thank you for your reply. At present, the cluster has switched the host network mode, and the ceph service can be accessed outside the k8s cluster.

**Comment by travisn** [comment]
Glad to hear it's working. Reopening to get this added to the rook documentation.

**Comment by zhucan** [comment]
@travisn is it possible to switch host network setting automatically after the network mode changed?

**Comment by travisn** [comment]
> @travisn is it possible to switch host network setting automatically after the network mode changed?

You're asking if the mons can be failed over automatically? It's possible, similar to what was done for #11578. It would just be good to have more validation/stabilization time for this transition so we know it's safe to automate.

**Comment by travisn** [comment]
We still need to get this documented (see [this comment](https://github.com/rook/rook/issues/11748#issuecomment-1449030639)) in the [mon failover guide](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-mon-health/#failing-over-a-monitor).

**Comment by Sheetalpamecha** [comment]
Hi @sp98, Are you currently working on it? If not, let me know I can pick it up.

**Comment by sp98** [comment]
I'm currently checking if we can automate this.

**Comment by anthonyeleven** [comment]
bump
