### ISSUE TITLE
Cluster on PVC rook-ceph-mon-endpoints not adding the Mon to the Monitor list⚠️

### ISSUE THREAD

**Issue by Jackiiiii** [rook/rook#15078]
Bug Report
Deviation from expected behavior:
Everything seems to work correctly, except that the monitors for the cluster on PVC are not being created properly.

The provisioner makes a request, but the CSI RBD responds with the following error:

```
I1130 15:14:50.322379 1 event.go:389] "Event occurred" object="rook-ceph/rook-ceph-mon-c" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Provisioning" message="External provisioner is provisioning volume for claim \"rook-ceph/rook-ceph-mon-c\""
I1130 15:14:50.327041 1 controller.go:951] "Retrying syncing claim" key="d808be5d-f7c0-43b7-a36a-6dee3f25a078" failures=358
E1130 15:14:50.327067 1 controller.go:974] error syncing claim "d808be5d-f7c0-43b7-a36a-6dee3f25a078": failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = InvalidArgument desc = failed to fetch monitor list using clusterID (rook-ceph): empty monitor list for cluster ID (rook-ceph) in config
I1130 15:14:50.327091 1 event.go:389] "Event occurred" object="rook-ceph/rook-ceph-mon-c" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ProvisioningFailed" message="failed to provision volume with StorageClass \"rook-ceph-block\": rpc error: code = InvalidArgument desc = failed to fetch monitor list using clusterID (rook-ceph): empty monitor list for cluster ID (rook-ceph) in config
In the endpoint file (yaml), the monitor list under DATA is empty ([EMPTY]).
Additionally, I had to manually add the CSI RBD secret key. It is unclear if this is normal behavior or not.
Although the PVCs for the monitors are created, the corresponding PVs are not being assigned.
```

Expected behavior:
The system should automatically create the PVCs for the monitors (this part works).
Afterward, the CSI RBD driver for the rook-block StorageClass should automatically assign the PVs.
How to reproduce it (minimal and precise):
The issue is hard to reproduce because the root cause is unclear.

I can, however, provide the necessary YAML files and logs for further investigation.
File(s) to submit:
Operator logs are attached.
Additional YAML files can be provided upon request.
Logs to submit:
Operator logs:
The relevant operator logs indicate that the monitor endpoints should be saved, but this does not seem to happen.

No msg: `kubectl -n rook-ceph logs rook-ceph-mon-a-canary-c59958f9c-67vch`

error: failed to fetch monitor list using clusterID (rook-ceph): empty monitor list for cluster ID (rook-ceph) in config

Cluster Status:
```
bash-5.1$ ceph status
unable to get monitor info from DNS SRV with service name: ceph-mon
2024-11-30T15:41:58.495+0000 7dcf3a000640 -1 failed for service _ceph-mon._tcp
2024-11-30T15:41:58.495+0000 7dcf3a000640 -1 monclient: get_monmap_and_config cannot identify monitors to contact
[errno 2] RADOS object not found (error connecting to the cluster)
```

error: unknown command "rook-ceph" for "kubectl"
Environment:
OS: Debian GNU/Linux 12 (bookworm)
Kernel: 6.8.4-2-pve
Cloud provider or hardware configuration: LXC: 2–3 CPUs, 2GB RAM (Test setup, later to be scaled to larger hardware)
Rook version: Latest version
Storage backend version: quay.io/ceph/ceph:v18.2.4
Kubernetes version:
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.31.3
Kubernetes cluster type: GKE

Storage backend status:
```
bash-5.1$ ceph health
unable to get monitor info from DNS SRV with service name: 2024-11-30T15:36:26.135+0000 742bc5200640 -1 failed for service _ceph-mon._tcp
2024-11-30T15:36:26.135+0000 742bc5200640 -1 monclient: get_monmap_and_config cannot identify monitors to contact
[errno 2] RADOS object not found (error connecting to the cluster)
```

**Comment by sp98** [comment]
@Jackiiiii Hi, can you share the complete rook-ceph-operator logs.

**Comment by Jackiiiii** [comment]
> @Jackiiiii Hi, can you share the complete rook-ceph-operator logs.

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph
data:
  ROOK_LOG_LEVEL: "INFO"
  ROOK_OPERATOR_METRICS_BIND_ADDRESS: "0"
  ROOK_CEPH_ALLOW_LOOP_DEVICES: "false"
  ROOK_USE_CSI_OPERATOR: "false"
  ROOK_CSI_ENABLE_CEPHFS: "true"
  ROOK_CSI_ENABLE_RBD: "true"
  ROOK_CSI_ENABLE_NFS: "false"
  ROOK_CSI_DISABLE_DRIVER: "false"
  CSI_ENABLE_ENCRYPTION: "false"
  CSI_ENABLE_METADATA: "true"
  CSI_PROVISIONER_REPLICAS: "2"
  CSI_ENABLE_CEPHFS_SNAPSHOTTER: "true"
  CSI_ENABLE_NFS_SNAPSHOTTER: "true"
  CSI_ENABLE_RBD_SNAPSHOTTER: "true"
  CSI_ENABLE_VOLUME_GROUP_SNAPSHOT: "true"
  CSI_FORCE_CEPHFS_KERNEL_CLIENT: "true"
  CSI_RBD_FSGROUPPOLICY: "File"
  CSI_CEPHFS_FSGROUPPOLICY: "File"
  CSI_NFS_FSGROUPPOLICY: "File"
  CSI_PLUGIN_ENABLE_SELINUX_HOST_MOUNT: "false"
  CSI_PLUGIN_PRIORITY_CLASSNAME: "system-node-critical"
  CSI_PROVISIONER_PRIORITY_CLASSNAME: "system-cluster-critical"
  CSI_ENABLE_LIVENESS: "false"
  ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"
  ROOK_ENABLE_DISCOVERY_DAEMON: "false"
  ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS: "15"
  CSI_ENABLE_CSIADDONS: "false"
  ROOK_WATCH_FOR_NODE_FAILURE: "true"
  CSI_GRPC_TIMEOUT_SECONDS: "150"
  CSI_ENABLE_TOPOLOGY: "false"
  CSI_CEPHFS_ATTACH_REQUIRED: "true"
  CSI_RBD_ATTACH_REQUIRED: "true"
  CSI_NFS_ATTACH_REQUIRED: "true"
  ROOK_DISABLE_DEVICE_HOTPLUG: "false"
  ROOK_DISCOVER_DEVICES_INTERVAL: "60m"
  ROOK_ENFORCE_HOST_NETWORK: "false"
  ROOK_CEPH_CLUSTER_NAME: "rook-ceph"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/component: rook-ceph-operator
    app.kubernetes.io/part-of: rook-ceph-operator
spec:
  selector:
    matchLabels:
      app: rook-ceph-operator
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: rook-ceph-operator
    spec:
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 5
      serviceAccountName: rook-ceph-system
      containers:
        - name: rook-ceph-operator
          image: docker.io/rook/ceph:master
          args: ["ceph", "operator"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 2016
            runAsGroup: 2016
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - mountPath: /var/lib/rook
              name: rook-config
            - mountPath: /etc/ceph
              name: default-config-dir
          env:
            - name: ROOK_CURRENT_NAMESPACE_ONLY
              value: "false"
            - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
              value: "false"
            - name: DISCOVER_DAEMON_UDEV_BLACKLIST
              value: "(?i)dm-[0-9]+,(?i)rbd[0-9]+,(?i)nbd[0-9]+"
            - name: ROOK_UNREACHABLE_NODE_TOLERATION_SECONDS
              value: "5"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: rook-config
          emptyDir: {}
        - name: default-config-dir
          emptyDir: {}
EOF
```

**Comment by BlaineEXE** [comment]
Santosh requested logs, but I see the deployment spec. Logs would be gotten with `kubectl --namespace rook-ceph logs deploy/rook-ceph-operator` or an equivalent command

**Comment by Jackiiiii** [comment]
I'm sorry, I misunderstood it because I read it wrong. By the way, is it normal that I have to create the service account myself and add the key for the RBD plugin provider? For the CSI, I don't need to do this—it just works.

the log auf the operator:
[rook-ceph-operator-c6d5b5d54-ld6l4.log](https://github.com/user-attachments/files/17981989/rook-ceph-operator-c6d5b5d54-ld6l4.log)

**Comment by sp98** [comment]
Operator has the same error: 
```
2024-11-30 15:19:48.095758 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2024-11-30 15:19:48.292952 E | ceph-cluster-controller: failed to get ceph daemons versions, this typically happens during the first cluster initialization. failed to run 'ceph versions'. . unable to get monitor info from DNS SRV with service name: ceph-mon
2024-11-30T15:19:48.283+0000 735827400640 -1 failed for service _ceph-mon._tcp
2024-11-30T15:19:48.283+0000 735827400640 -1 monclient: get_monmap_and_config cannot identify monitors to contact
[errno 2] RADOS object not found (error connecting to the cluster): exit status 1
```

**Comment by Jackiiiii** [comment]
Yeah the question would be why? and i found in the mon endpoint yaml that is automatic created in the part data: monitor[its empty] but i have no idea why.

**Comment by BlaineEXE** [comment]
This is expressing like a networking issue. If the hardware is a linux container (LXC), then I'm not sure if that could be a factor.

Santosh mentioned that a similar issue was resolved by upgrading the Ubuntu version from 18 to 20. Maybe try that?

**Comment by Jackiiiii** [comment]
I'm using Debian and it should be the newest image so do you think I should change too Ubuntu? Cause actually everything work beside that. Or is it maybe because proxmox providing LXC?

**Comment by sp98** [comment]
> I'm using Debian and it should be the newest image so do you think I should change too Ubuntu? Cause actually everything work beside that. Or is it maybe because proxmox providing LXC?

@Jackiiiii Can you test this on a different OS by any chance. That will confirm if this is an environment specific behavior or not.  Maybe try ubuntu 20.x.

**Comment by Jackiiiii** [comment]
@sp98 Thats no problem too use other OS, i will do it when i m back home but i have also seen some settings that i dont use i think like # CSI_ENABLE_HOST_NETWORK: "true" is that also a problem or is it not needed?

**Comment by Jackiiiii** [comment]
Well i have change everything too Ubuntu, didnt expect that i need to change some other stuff too then but that didnt fix anything even have used that CSI KernelMountOptions: "ms_mode=prefer-crc", still same errors.

[csi-rbdplugin-provisioner-7c4554c7f6-c7txh.log](https://github.com/user-attachments/files/18013708/csi-rbdplugin-provisioner-7c4554c7f6-c7txh.log)
[rook-ceph-operator-5f68d9fbc6-sk4gr.log](https://github.com/user-attachments/files/18013709/rook-ceph-operator-5f68d9fbc6-sk4gr.log)

**Comment by Jackiiiii** [comment]
> > I'm using Debian and it should be the newest image so do you think I should change too Ubuntu? Cause actually everything work beside that. Or is it maybe because proxmox providing LXC?
> 
> @Jackiiiii Can you test this on a different OS by any chance? That will confirm if this is an environment specific behavior or not. I was referring to another [issue](https://github.com/rook/rook/issues/14989) with same error that got fixed by updating the OS.
> 
> Also, check if [this](https://github.com/rook/rook/issues/11521#issuecomment-1737174422) helps.

Did you actually mean the LXC OS or the main system hosting the LXC? I set up Ubuntu inside an LXC container, but it didn’t work. I manage around 30 servers. If you mean the main system, which is Proxmox (Debian), that would be a disaster because I’m using a script that automates everything without requiring manual intervention.

I created four test servers to experiment with Rook-Ceph before deploying it on my main cloud system, and I’m really glad I didn’t proceed because this would have been a major issue. I’ve been working on this for about three weeks now. I still don’t know what the problem is, and I really need help. Is there an alternative solution?
