### ISSUE TITLE
reinstalling rook-ceph-cluster with ceph19.2 image  is failing with "osd already exists with old ceph cluster" ERROR

### ISSUE THREAD

**Issue by karthik1989** [rook/rook#15937]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
rook-ceph-cluster was installed with rook-ceph-cluster-v1.16.5.tgz
Uninstalled the rook-ceph-cluster 
Cleaned up the hosts ( rm -rf /var/lib/rook , wipefs -a /dev/<ceph disk>
Reinstall rook-ceph-cluster 
osd-prepare job is failing with below ERROR

2025-05-23 17:08:26.934324 I | cephosd: configuring new raw device "/dev/sdb"
2025-05-23 17:08:26.934347 D | exec: Running command: stdbuf -oL ceph-volume raw prepare --bluestore --data /dev/sdb
2025-05-23 17:08:27.737334 I | cephosd: --> Raw device /dev/sdb is already prepared.
2025-05-23 17:08:27.737572 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json
2025-05-23 17:08:28.001247 D | cephosd: {}
2025-05-23 17:08:28.001279 I | cephosd: 0 ceph-volume lvm osd devices configured on this node
2025-05-23 17:08:28.001302 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log raw list --format json
2025-05-23 17:08:30.852479 D | cephosd: {
    "2867c9a0-7368-417f-ae38-0e424336bbaa": {
        "ceph_fsid": "7226e8c0-06a7-4bae-8686-643f7e69a074",
        "device": "/dev/sdb",
        "osd_id": 2,
        "osd_uuid": "2867c9a0-7368-417f-ae38-0e424336bbaa",
        "type": "bluestore"
    }
}
2025-05-23 17:08:30.852651 I | cephosd: skipping osd.2: "2867c9a0-7368-417f-ae38-0e424336bbaa" belonging to a different ceph cl  uster "7226e8c0-06a7-4bae-8686-643f7e69a074"

**Expected behavior:**
Proper reinstallation of ceph on uninstallation ( if possible , autoclear of host ceph data wipefs and rm -rf /var/lib/rook)

**How to reproduce it (minimal and precise):**

images used:
cephv1.16.5.tar
cephv19.2.1.tar
csi-resizerv1.13.1.tar
csi-attacherv4.8.0.tar
cephcsiv3.13.0.tar
csi-provisionerv5.1.0.tar
csi-snapshotterv8.2.0.tar
csi-node-driver-registrarv2.13.0.tar

Charts used:
rook-ceph-v1.16.5.tgz
rook-ceph-cluster-v1.16.5.tgz

Command -
Install rook-ceph-cluster
================
helm install rook-ceph rook-ceph-v1.16.5.tgz -n rook-ceph
helm install rook-ceph-cluster rook-ceph-cluster-v1.16.5.tgz -n rook-ceph

Uninstall rook-ceph-cluster After installation is completed with all osd pods up and running
===========================================================

helm uninstall rook-ceph-cluster -n rook-ceph
helm uninstall rook-ceph -n rook-ceph

After this cleanup ceph data and device on the osd hosts
rm -rf /var/lib/rook
wipefs -a /dev/<ceph disk>

Install rook-ceph-operator again:
======================
helm install rook-ceph rook-ceph-v1.16.5.tgz -n rook-ceph
helm install rook-ceph-cluster rook-ceph-cluster-v1.16.5.tgz -n rook-ceph

After this osd pods are not coming up as below error is seen in osd-prepare jobs

2025-05-23 17:08:26.934324 I | cephosd: configuring new raw device "/dev/sdb"
2025-05-23 17:08:26.934347 D | exec: Running command: stdbuf -oL ceph-volume raw prepare --bluestore --data /dev/sdb
2025-05-23 17:08:27.737334 I | cephosd: --> Raw device /dev/sdb is already prepared.
2025-05-23 17:08:27.737572 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json
2025-05-23 17:08:28.001247 D | cephosd: {}
2025-05-23 17:08:28.001279 I | cephosd: 0 ceph-volume lvm osd devices configured on this node
2025-05-23 17:08:28.001302 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log raw list --format json
2025-05-23 17:08:30.852479 D | cephosd: {
    "2867c9a0-7368-417f-ae38-0e424336bbaa": {
        "ceph_fsid": "7226e8c0-06a7-4bae-8686-643f7e69a074",
        "device": "/dev/sdb",
        "osd_id": 2,
        "osd_uuid": "2867c9a0-7368-417f-ae38-0e424336bbaa",
        "type": "bluestore"
    }
}
2025-05-23 17:08:30.852651 I | cephosd: skipping osd.2: "2867c9a0-7368-417f-ae38-0e424336bbaa" belonging to a different ceph cl  uster "7226e8c0-06a7-4bae-8686-643f7e69a074"

 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): HP gen10 blade and RHCOS (4.16)
* Kernel (e.g. `uname -a`): 
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 5.14.0-427.55.1.el9_4.x86_64
* Storage backend version (e.g. for ceph do `ceph -v`): 19.2 image
* Kubernetes version (use `kubectl version`): 1.29
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): openshift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by sp98** [comment]
@karthik1989 The OSD disks were not cleaned up properly from the previous install and `wipefs -a /dev/` won't suffice. That's why you see this issue.

Due to recent ceph changes, OSD metadata is duplicated across multiple locations on the disk (0, 10G, 100G etc).  [Documentation](https://rook.io/docs/rook/latest-release/Getting-Started/ceph-teardown/?h=cleanup#zapping-devices) was updated to reflect this change. You can follow this documentation to clean up the disks are uninstalling rook-ceph.

A couple of automation efforts to fix this are in progress 
- [Fixing the disk cleanup via cleanup jobs during the uninstall process](https://github.com/rook/rook/pull/15666)
- [Force deployment of OSDs on disks that have leftovers from a previous install](https://github.com/rook/rook/issues/15523).

**Comment by karthik1989** [comment]
So, you are suggesting only to execute dd command which is dangerous .
Any other WA where it will check the disk usage and then clear like wipefs ? Because wipefs will not wipe busy devices

Anyway automation also not working.
in which version this automation of cleanup works will be completed

Thanks,
Karthik

**Comment by kgfathur** [comment]
Hello,

I found the same issue and can be solved without deleting the **rook-ceph operator** or **rook-ceph cluster**.

On my 3 node cluster with 1 osd disk only (/dev/vdb):
1. Check disk inventory:
```bash
$ kubectl get pod -A -l app=rook-ceph-mon -o jsonpath={.items[*].metadata.name} | tr ' ' '\n' | xargs -I{} kubectl exec -n rook-ceph {} -c mon -- ceph-volume inventory --list-all

Device Path               Size         Device nodes    rotates available Model name
/dev/vda                  120.00 GB    vda             True    False
/dev/vda1                 1.00 MB      vda             False   False
/dev/vda2                 127.00 MB    vda             False   False
/dev/vda3                 384.00 MB    vda             False   False
/dev/vda4                 119.50 GB    vda             False   False
/dev/vdb                  60.00 GB     vdb             True    False

Device Path               Size         Device nodes    rotates available Model name
/dev/vda                  120.00 GB    vda             True    False
/dev/vda1                 1.00 MB      vda             False   False
/dev/vda2                 127.00 MB    vda             False   False
/dev/vda3                 384.00 MB    vda             False   False
/dev/vda4                 119.50 GB    vda             False   False
/dev/vdb                  60.00 GB     vdb             True    False

Device Path               Size         Device nodes    rotates available Model name
/dev/vda                  120.00 GB    vda             True    False
/dev/vda1                 1.00 MB      vda             False   False
/dev/vda2                 127.00 MB    vda             False   False
/dev/vda3                 384.00 MB    vda             False   False
/dev/vda4                 119.50 GB    vda             False   False
/dev/vdb                  60.00 GB     vdb             True    False
```
2. Verify disk that still hold old cluster's metadata 
```bash
$ kubectl get pod -A -l app=rook-ceph-mon -o jsonpath={.items[*].metadata.name} | tr ' ' '\n' | xargs -I{} kubectl exec -n rook-ceph {} -c mon -- ceph-volume raw list
{
    "ceeef661-b549-4fca-be7b-d5a410aa97be": {
        "ceph_fsid": "b20be126-161c-4035-9bf1-1730953a031f",
        "device": "/dev/vdb",
        "osd_id": 2,
        "osd_uuid": "ceeef661-b549-4fca-be7b-d5a410aa97be",
        "type": "bluestore"
    }
}
{
    "1d8f6096-71ba-433a-a2a1-8f3d9dbcb4ea": {
        "ceph_fsid": "b20be126-161c-4035-9bf1-1730953a031f",
        "device": "/dev/vdb",
        "osd_id": 0,
        "osd_uuid": "1d8f6096-71ba-433a-a2a1-8f3d9dbcb4ea",
        "type": "bluestore"
    }
}
{
    "74105e3f-4890-4879-9762-985bd2fefda5": {
        "ceph_fsid": "b20be126-161c-4035-9bf1-1730953a031f",
        "device": "/dev/vdb",
        "osd_id": 1,
        "osd_uuid": "74105e3f-4890-4879-9762-985bd2fefda5",
        "type": "bluestore"
    }
}
```

3. Zap the disk using ceph-volume:
```bash
$ kubectl get pod -A -l app=rook-ceph-mon -o jsonpath={.items[*].metadata.name} | tr ' ' '\n' | xargs -I{} kubectl exec -n rook-ceph {} -c mon -- ceph-volume lvm zap /dev/vdb --destroy
--> Zapping: /dev/vdb
--> Removing all BlueStore signature on /dev/vdb if any...
Running command: /usr/bin/ceph-bluestore-tool zap-device --dev /dev/vdb --yes-i-really-really-mean-it
Running command: /usr/bin/dd if=/dev/zero of=/dev/vdb bs=1M count=10 conv=fsync
 stderr: 10+0 records in
10+0 records out
 stderr: 10485760 bytes (10 MB, 10 MiB) copied, 0.0095401 s, 1.1 GB/s
--> Zapping successful for: <Raw Device: /dev/vdb>

--> Zapping: /dev/vdb
--> Removing all BlueStore signature on /dev/vdb if any...
Running command: /usr/bin/ceph-bluestore-tool zap-device --dev /dev/vdb --yes-i-really-really-mean-it
Running command: /usr/bin/dd if=/dev/zero of=/dev/vdb bs=1M count=10 conv=fsync
 stderr: 10+0 records in
10+0 records out
 stderr: 10485760 bytes (10 MB, 10 MiB) copied, 0.0091466 s, 1.1 GB/s
--> Zapping successful for: <Raw Device: /dev/vdb>

--> Zapping: /dev/vdb
--> Removing all BlueStore signature on /dev/vdb if any...
Running command: /usr/bin/ceph-bluestore-tool zap-device --dev /dev/vdb --yes-i-really-really-mean-it
Running command: /usr/bin/dd if=/dev/zero of=/dev/vdb bs=1M count=10 conv=fsync
 stderr: 10+0 records in
10+0 records out
 stderr: 10485760 bytes (10 MB, 10 MiB) copied, 0.0100276 s, 1.0 GB/s
--> Zapping successful for: <Raw Device: /dev/vdb>
```

However, sometimes still need to execute some of command bellow because the disks are not empty.
```bash
$ wipefs -af /dev/vdb;
$ sgdisk --zap-all /dev/vdb;
$ blkdiscard /dev/vdb;
```
Check on this [documentation](https://rook.io/docs/rook/latest-release/Getting-Started/ceph-teardown/#zapping-devices).

Don't forget to clean `/var/lib/rook/` as well

**Comment by ktoulliou** [comment]
Same problem with SAS disks (non-RAID devices of type megaraid_sas).

But NVME is compatible with this sanitization procedure.

Procedure:
- patch ceph-cluster + remove ceph-cluster + delete operator
- on each disk : sgdisk --zapp-all + dd + blkdiscard + partprobe
- remove /var/lib/rook
- reinstall

Some metadata resists this sanitization procedure for SAS disks.
```
2025-09-19 13:07:26.943486 I | cephosd: skipping osd.9: "dc33bdae-16a7-49ba-8cc4-236b6d4fdcc5" belonging to a different ceph cluster "ae2be176-cf68-4cf0-9f3d-518fe7eac019"
2025-09-19 13:07:26.943504 I | cephosd: skipping osd.106: "5a58d298-8f39-4dd7-bd41-6424d7d274db" belonging to a different ceph cluster "ae2be176-cf68-4cf0-9f3d-518fe7eac019"
2025-09-19 13:07:26.943516 I | cephosd: skipping osd.81: "5b0da6b9-2489-4aef-9519-b140574ad2e3" belonging to a different ceph cluster "ae2be176-cf68-4cf0-9f3d-518fe7eac019"
2025-09-19 13:07:26.943527 I | cephosd: skipping osd.34: "7c9578db-6e61-40cf-807d-5927e5c41be7" belonging to a different ceph cluster "ae2be176-cf68-4cf0-9f3d-518fe7eac019"
2025-09-19 13:07:26.958341 I | cephosd: setting device type "nvme" for device "/dev/nvme2n1"
2025-09-19 13:07:26.958356 I | cephosd: setting device class "nvme" for device "/dev/nvme2n1"
2025-09-19 13:07:26.958375 I | cephosd: skipping osd.43: "d8344033-2583-4e91-b9ef-03b59877c213" belonging to a different ceph cluster "ae2be176-cf68-4cf0-9f3d-518fe7eac019"
2025-09-19 13:07:26.958386 I | cephosd: skipping osd.57: "ef7193c1-5e74-4d2f-9a71-6053a96f2c87" belonging to a different ceph cluster "ae2be176-cf68-4cf0-9f3d-518fe7eac019"
2025-09-19 13:07:26.958397 I | cephosd: skipping osd.93: "437d1438-00ca-46d8-bf06-b1969d5c4d25" belonging to a different ceph cluster "ae2be176-cf68-4cf0-9f3d-518fe7eac019"
2025-09-19 13:07:26.958407 I | cephosd: skipping osd.18: "84322b4a-44b2-46cf-b8cb-2d853edaaf07" belonging to a different ceph cluster "ae2be176-cf68-4cf0-9f3d-518fe7eac019"
2025-09-19 13:07:26.958416 I | cephosd: skipping osd.3: "dc0232c3-e516-4062-b67a-c5ec247d4d77" belonging to a different ceph cluster "ae2be176-cf68-4cf0-9f3d-518fe7eac019"
2025-09-19 13:07:26.958424 I | cephosd: 1 ceph-volume raw osd devices configured on this node
 ```

I'm using Talos Linux OS.

**Comment by travisn** [comment]
This should be fixed now in the [Cleanup guide](https://rook.io/docs/rook/latest-release/Getting-Started/ceph-teardown/#zapping-devices) to wipe all the necessary disk offsets, and also #15666 is merged for the uninstall cleanup job. 

@ktoulliou What version of Rook are you running, and did you try the latest cleanup guide?

**Comment by ktoulliou** [comment]
@travisn is the latest version available on artifact hub. I’m trying to fully redeploy rook and OSDs this week on 100+ SAS devices, 30+ nvme drives for 10+ baremetal servers with k8s 1.33.4.

Yes i’ve followed cleanup guide

**Comment by travisn** [comment]
@sp98 Any other ideas for what is missing with the cleanup?

**Comment by ktoulliou** [comment]
I have found this logs in `osd-prepare` pods after rollout restart rook-ceph-operator deployement. For example with sdh :

```
2025-09-22 09:30:53.662239 I | cephosd: configuring new raw device "/dev/sdh"
2025-09-22 09:30:53.662280 D | exec: Running command: stdbuf -oL ceph-volume raw prepare --bluestore --data /dev/sdh --crush-device-class ceph-cold
2025-09-22 09:30:54.878198 I | cephosd: --> Raw device /dev/sdh is already prepared.
...
2025-09-22 09:11:27.118597 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log raw list --format json
2025-09-22 09:11:36.088371 D | cephosd: {
...
    "d8344033-2583-4e91-b9ef-03b59877c213": {
        "ceph_fsid": "ae2be176-cf68-4cf0-9f3d-518fe7eac019",
        "device": "/dev/sdh",
        "osd_id": 43,
        "osd_uuid": "d8344033-2583-4e91-b9ef-03b59877c213",
        "type": "bluestore"
...
2025-09-22 09:11:36.099276 I | cephosd: skipping osd.43: "d8344033-2583-4e91-b9ef-03b59877c213" belonging to a different ceph cluster "ae2be176-cf68-4cf0-9f3d-518fe7eac019"
```

I tried the cleanup guide again, the `sg_sanitize` command, and then rebooted the host, but still the same logs and problems. Or maybe `sg_sanitize` is the solution, but I don't know what parameters to use.

**Comment by ktoulliou** [comment]
The workaround I found is to run `ceph-volume lvm zap /host/dev/sda` (/host because i'm in a pod) for each SAS disks on each servers.

```bash
$ ceph-volume lvm zap /host/dev/sda
stderr: Unknown device "/host/dev/sda": No such device
--> Zapping: /host/dev/sda
--> --destroy was not specified, but zapping a whole device will remove the partition table
--> Removing all BlueStore signature on /host/dev/sda if any...
Running command: /usr/bin/ceph-bluestore-tool zap-device --dev /host/dev/sda --yes-i-really-really-mean-it
Running command: /usr/bin/dd if=/dev/zero of=/host/dev/sda bs=1M count=10 conv=fsync
stderr: 10+0 records in
10+0 records out
stderr: 10485760 bytes (10 MB, 10 MiB) copied, 0.0680949 s, 154 MB/s
--> Zapping successful for: <Raw Device: /host/dev/sda>
```

Maybe the `Removing all BlueStore signature` tasks don't work with standards cleanup ?

**Comment by sp98** [comment]
> Same problem with SAS disks (non-RAID devices of type megaraid_sas).
> 
> But NVME is compatible with this sanitization procedure.
> 
> Procedure:
> 
> * patch ceph-cluster + remove ceph-cluster + delete operator
> * on each disk : sgdisk --zapp-all + dd + blkdiscard + partprobe

@ktoulliou Can you confirm if the `dd` operation was performed on all the offsets of the disk. 

Also, confirm if no bluestore signatures were present on the disk after you performed to disk cleanup as mentioned in [this doc. ](https://rook.io/docs/rook/latest-release/Getting-Started/ceph-teardown/#zapping-devices) For example: if the disk still has bluestore metadata from the previous OSD, then you will see something like: 

Before cleanup. 
```
sh-5.1# hexdump -C -s 1073741824 -n 22 /dev/sda5
40000000  62 6c 75 65 73 74 6f 72  65 20 62 6c 6f 63 6b 20  |bluestore block |
40000010  64 65 76 69 63 65                                 |device|
40000016
sh-5.1# hexdump -C -s 10737418240 -n 22 /dev/sda5
280000000  62 6c 75 65 73 74 6f 72  65 20 62 6c 6f 63 6b 20  |bluestore block |
280000010  64 65 76 69 63 65                                 |device|
280000016
sh-5.1# hexdump -C -s 107374182400 -n 22 /dev/sda5
1900000000  62 6c 75 65 73 74 6f 72  65 20 62 6c 6f 63 6b 20  |bluestore block |
1900000010  64 65 76 69 63 65                                 |device|
1900000016
sh-5.1# hexdump -C -s 1073741824000 -n 22 /dev/sda5
fa00000000  62 6c 75 65 73 74 6f 72  65 20 62 6c 6f 63 6b 20  |bluestore block |
fa00000010  64 65 76 69 63 65                                 |device|
fa00000016
```

And after cleanup these metadata should be gone
```
## after cleanup 

sh-5.1# hexdump -C -s 1073741824 -n 22 /dev/sda5
40000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
40000010  00 00 00 00 00 00                                 |......|
40000016
sh-5.1# hexdump -C -s 10737418240 -n 22 /dev/sda5
280000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
280000010  00 00 00 00 00 00                                 |......|
280000016
sh-5.1# hexdump -C -s 107374182400 -n 22 /dev/sda5
1900000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
1900000010  00 00 00 00 00 00                                 |......|
1900000016
sh-5.1# hexdump -C -s 1073741824000 -n 22 /dev/sda5
fa00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
fa00000010  00 00 00 00 00 00                                 |......|
fa00000016
sh-5.1#
```


- Rook recently introduced a new feature called [WipeDevicesFromPreviousClusters](https://github.com/rook/rook/blob/a315a37ccf594d980ae13aaca06e18337d461ed7/pkg/apis/ceph.rook.io/v1/types.go#L3230). If set to `true`, this will just cleanup the disks that have metadata from another cluster by using `ceph-volume lvm zap <diskName>`.  But this new feature is not required if the cleanup of the disks is done after the previous reinstall.

**Comment by sp98** [comment]
@ktoulliou checking again about my previous comment ^^

**Comment by Ricardo2001ZG** [comment]
> [@sp98](https://github.com/sp98) Any other ideas for what is missing with the cleanup?

Still have problems.
When OSDs are deployed on raw partitions, performing cleanup operations fails to identify the metadata under the partition, preventing proper cleanup.
This is because for raw partitions, there is an offset to the starting partition in the partition table, causing the sectors cleaned for the raw partition to be misaligned compared to those on a raw disk.

As shown in the following commands:

```shell
# Test Result
root@ceph-1:~# hexdump -C -s 1073741824 -n 22 /dev/sdb
40000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
40000010  00 00 00 00 00 00                                 |......|
40000016
root@ceph-1:~# hexdump -C -s 1073741824 -n 22 /dev/sdb1
40000000  62 6c 75 65 73 74 6f 72  65 20 62 6c 6f 63 6b 20  |bluestore block |
40000010  64 65 76 69 63 65                                 |device|
40000016
```

In this scenario, cleanup cannot correctly remove the metadata, resulting in the system still detecting metadata labels when attempting to rebuild the cluster.
