### ISSUE TITLE
op-bucket-prov tries to create wrong ceph user for existed buckets and OBC after upgrading from rook v1.15.7 to v1.16.8

### ISSUE THREAD

**Issue by grapemix** [rook/rook#16202]
**Is this a bug report or feature request?**
op-bucket-prov tries to create wrong ceph user for existed buckets and OBC after upgrading from rook v1.15.7 to v1.16.8. Please provide procedures for me to fix it.

**Deviation from expected behavior:**
I would expected rook will recognized my existed buckets and OBC and its owner just like I upgrade from v1.14.x to v1.15.7. 

**Expected behavior:**
For example, one of my bucket is called family-media-bk in a namespace called backup.
The existed owner of the bucket is called obc-backup-family-media-bk-XXXXX-7686-4504-80c1-3a3287bb8976, but rook now creates a new user called obc-rook-ceph-family-media-bk-XXXXX-6e5a-4f17-a7cb-42c6f04bba2e and hence I got error.

** Further deep dive **
Here is the relevant log from rook-operator.
```
controller.go:217] "msg"="reconciling claim" "key"="rook-ceph/family-media-bk"
helpers.go:107] "msg"="getting claim for key" "key"="rook-ceph/family-media-bk"
helpers.go:213] "msg"="getting ObjectBucketClaim's StorageClass" "key"="rook-ceph/family-media-bk"
helpers.go:218] "msg"="got StorageClass" "key"="rook-ceph/family-media-bk" "name"="fast-ceph-bucket"
controller.go:270] "msg"="syncing obc creation" "key"="rook-ceph/family-media-bk"
controller.go:552] "msg"="updating OBC metadata" "key"="rook-ceph/family-media-bk"
resourcehandlers.go:277] "msg"="updating" "key"="rook-ceph/family-media-bk" "obc"="rook-ceph/family-media-bk"
controller.go:341] "msg"="provisioning" "bucket"="family-media-bk" "key"="rook-ceph/family-media-bk"
 op-bucket-prov: initializing and setting CreateOrGrant services
 op-bucket-prov: getting storage class "fast-ceph-bucket"
 op-bucket-prov: Provision: creating bucket "family-media-bk" for OBC "family-media-bk"
 op-bucket-prov: creating Ceph user "obc-rook-ceph-family-media-bk-XXXXX-6e5a-4f17-a7cb-42c6f04bba2e"
 op-bucket-prov: successfully created Ceph user "obc-rook-ceph-family-media-bk-XXXXX-6e5a-4f17-a7cb-42c6f04bba2e" with access keys
controller.go:204] "Unhandled Error" err="error syncing 'rook-ceph/family-media-bk': error provisioning bucket: bucket \"family-media-bk\" already exists and is owned by \"obc-backup-family-media-bk-XXXXX-7686-4504-80c1-3a3287bb8976\" for different OBC, requeuing" logger="UnhandledError"
```

cluster is healthy and have plenty of space. I will explain the daemons crash later.
```
ceph -s
  cluster:
    id:     e41b39de-2f12-4d3c-b3a8-7409fe2XXXXX
    health: HEALTH_WARN
            2 daemons have recently crashed
 
  services:
    mon: 3 daemons, quorum d,h,c (age 10h)
    mgr: a(active, since 10h), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 4 osds: 4 up (since 10h), 4 in (since 40h)
    rgw: 1 daemon active (1 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   12 pools, 85 pgs
    objects: 534.25k objects, 1.6 TiB
    usage:   2.7 TiB used, 4.3 TiB / 7.0 TiB avail
    pgs:     85 active+clean
 
  io:
    client:   1.3 KiB/s rd, 266 KiB/s wr, 2 op/s rd, 9 op/s wr
```

OBC which namespace is always backup.
```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  creationTimestamp: "2024-08-30T02:55:05Z"
  finalizers:
  - objectbucket.io/finalizer
  generation: 2
  labels:
    bucket-provisioner: rook-ceph.ceph.rook.io-bucket
    kustomize.toolkit.fluxcd.io/name: stor-rook-ceph-cluster
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: family-media-bk
  namespace: backup
  resourceVersion: "26486"
  uid: XXXXXX
spec:
  additionalConfig:
    maxObjects: "100000"
    maxSize: 512G
  bucketName: family-media-bk
  objectBucketName: obc-backup-family-media-bk
  storageClassName: fast-ceph-bucket
status:
  phase: Bound
```

No change in storageClass.
```
kubectl get storageClass -A
NAME                        PROVISIONER                            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
fast-ceph-block (default)   rook-ceph.rbd.csi.ceph.com             Delete          Immediate              true                   334d
fast-ceph-bucket            rook-ceph.ceph.rook.io/bucket          Delete          Immediate              false                  334d
fast-ceph-filesystem        rook-ceph.cephfs.csi.ceph.com          Delete          Immediate              true                   83d
```

Both ceph users existed
```
radosgw-admin user list |grep family-media-bk
"obc-backup-family-media-bk-XXXXX-7686-4504-80c1-3a3287bb8976",
"obc-rook-ceph-family-media-bk-XXXXX-6e5a-4f17-a7cb-42c6f04bba2e",
```

I can still see contents from s3 endpoints by s5cmd.

But I cannot find any buckets.
```
kubectl get bucket -A
No resources found
```

Bucket details from `radosgw-admin bucket stats`
```
{
  "bucket": "family-media-bk",
  "tenant": "",
  "versioning": "off",
  "zonegroup": "215346aa-d0f3-415e-XXXXX-f0bbe563828b",
  "placement_rule": "default-placement",
  "explicit_placement": {
    "data_pool": "",
    "data_extra_pool": "",
    "index_pool": ""
  },
  "id": "a7736693-cfe0-4767-XXXXX-526f67996f87.16286.8",
  "marker": "a7736693-cfe0-4767-XXXXX-526f67996f87.16286.8",
  "index_type": "Normal",
  "index_generation": 0,
  "num_shards": 11,
  "object_lock_enabled": false,
  "mfa_enabled": false,
  "owner": "obc-backup-family-media-bk-XXXXX-7686-4504-80c1-3a3287bb8976",
  "ver": "0#1,1#1,2#1,3#1,4#1,5#1,6#1,7#1,8#1,9#1,10#1",
  "master_ver": "0#0,1#0,2#0,3#0,4#0,5#0,6#0,7#0,8#0,9#0,10#0",
  "mtime": "2025-07-30T15:24:43.821661Z",
  "creation_time": "2024-08-30T03:03:57.973977Z",
  "max_marker": "0#,1#,2#,3#,4#,5#,6#,7#,8#,9#,10#",
  "usage": {},
  "bucket_quota": {
    "enabled": false,
    "check_on_raw": false,
    "max_size": -1,
    "max_size_kb": 0,
    "max_objects": -1
  }
}
```

**How to reproduce it (minimal and precise):**
Upgrading rook operator from v1.15.7 to v1.16.8. Then upgrading rook cluster from v1.15.7 to v1.16.8.

I've changed the mon's node IP about a days before and hence the status showed 2 daemons have recently crashed. After following https://docs.ceph.com/en/latest/rados/operations/add-or-rm-mons/, mons seems working fine. (No err, `ceph -s` looks fine, other things like pvc works fine). I did have to change a few cm and secret manually. I did check the env var of all related pod manually. So I think changing mons' ip is unrelated to this bug.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
Relevant helm values (no change during upgrade):
```
cephObjectStores:
  - name: fast-ceph-objectstore
    ingress:
      enabled: false
    spec:
      metadataPool:
        failureDomain: host
        replicated:
          size: 3
      dataPool:
        failureDomain: host
        deviceClass: ssd
        erasureCoded:
          dataChunks: 2
          codingChunks: 1
      preservePoolsOnDelete: true
      gateway:
        port: 80
        hostNetwork: false
        resources:
          requests:
            cpu: 100m
            memory: 128M
          limits:
            memory: 2Gi
        instances: 1
        priorityClassName: system-cluster-critical
      healthCheck:
        bucket:
          interval: 60s
    storageClass:
      enabled: true
      name: fast-ceph-bucket
      reclaimPolicy: Delete
      parameters:
        region: us-east-1
```

**Cluster Status to submit**:

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 24.04
* Kernel (e.g. `uname -a`): Linux 6.8.0-64-generic
* Cloud provider or hardware configuration: homelab/bare metal
* Rook version (use `rook version` inside of a Rook Pod): v1.16.8 (from rook-operator)
* Storage backend version (e.g. for ceph do `ceph -v`): 19.2.2 squid
* Kubernetes version (use `kubectl version`): v1.31.7+k3s1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox]: good

**Comment by BlaineEXE** [comment]
Could you also show the yaml output for the corresponding ObjectBucket resource `obc-backup-family-media-bk`? 

Contextually, there is `AdditionalState` set on the OB, and that additional state is supposed to contain the object user that corresponds to the OBC. I suspect that has become lost somehow.

In our Rook CI (and downstream Red Hat CI), I haven't seen this get lost, but OBC metadata like this has been added/changed over time, so it's entirely possible.

With the OB info, I'll hopefully be able to provide guidance on how to recover your OBC health, and if possible figure out how it happened to resolve it.

**Comment by grapemix** [comment]
Thanks for your quick reply.

```
kubectl get ObjectBucket  obc-backup-family-media-bk -o yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucket
metadata:
  creationTimestamp: "2024-08-30T03:03:58Z"
  finalizers:
  - objectbucket.io/finalizer
  generation: 1
  labels:
    bucket-provisioner: rook-ceph.ceph.rook.io-bucket
  name: obc-backup-family-media-bk
  resourceVersion: "26474"
  uid: XXXXXX-c1fe-4758-a571-2cfd0969b7a9
spec:
  additionalState:
    cephUser: obc-backup-family-media-bk-XXXXXX-7686-4504-80c1-3a3287bb8976
    objectStoreName: fast-ceph-objectstore
    objectStoreNamespace: rook-ceph
  claimRef:
    apiVersion: objectbucket.io/v1alpha1
    kind: ObjectBucketClaim
    name: family-media-bk
    namespace: backup
    uid: XXXXXX-7686-4504-80c1-3a3287bb8976
  endpoint:
    additionalConfig:
      maxObjects: "100000"
      maxSize: 512G
    bucketHost: rook-ceph-rgw-fast-ceph-objectstore.rook-ceph.svc
    bucketName: family-media-bk
    bucketPort: 80
    region: ""
    subRegion: ""
  reclaimPolicy: Delete
  storageClassName: fast-ceph-bucket
status:
  phase: Bound
```
OBC for easy comparison:
```
kubectl get obc -n backup family-media-bk -o yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  creationTimestamp: "2024-08-30T02:55:05Z"
  finalizers:
  - objectbucket.io/finalizer
  generation: 2
  labels:
    bucket-provisioner: rook-ceph.ceph.rook.io-bucket
    kustomize.toolkit.fluxcd.io/name: stor-rook-ceph-cluster
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: family-media-bk
  namespace: backup
  resourceVersion: "26486"
  uid: XXXXXX-7686-4504-80c1-3a3287bb8976
spec:
  additionalConfig:
    maxObjects: "100000"
    maxSize: 512G
  bucketName: family-media-bk
  objectBucketName: obc-backup-family-media-bk
  storageClassName: fast-ceph-bucket
status:
  phase: Bound
```
It seems the uid of OBC match w/ ObjectBucket's claimRef.uid, suffix of ObjectBucket's additionalState.cephUser,  radosgw's bucket owner and the correct existed ceph user.

On the other hand, the suffix of new ceph user(XXXXX-6e5a-4f17-a7cb-42c6f04bba2e) and ObjectBucket's uid (XXXXXX-c1fe-4758-a571-2cfd0969b7a9) don't fit/match anything.

So the OB's additionalState.cephUser looks correct. Based on the creationTimestamp of OB, OBC, and the radosgw's user, all these resources have been created in the same time.

In my rook-operator's helm file, I have not set rbacAggregate.enableOBCs. In other words, I left this param as default. I am not sure if it is related.

Let me know if you want more info. Thanks.

**Comment by BlaineEXE** [comment]
🤔 interesting. I'm glad to know that the OB has the right info. But now, I'm not sure what is going wrong in Rook that this is happening. I'd like to take a look at deeper logs with `ROOK_LOG_LEVEL=DEBUG` set. Could you set that and copy those logs here? It might be helpful to also have 20 lines before and after, just in case other info is relevant

**Comment by grapemix** [comment]
I am surprised the right info of the OB too.

Since I use helm, I assume ROOK_LOG_LEVEL is equivalent to rook-ceph operator helm chart's logLevel. Here is the relevant log:
```
controller.go:217] "msg"="reconciling claim" "key"="backup/family-media-bk"
helpers.go:107] "msg"="getting claim for key" "key"="backup/family-media-bk"
helpers.go:213] "msg"="getting ObjectBucketClaim's StorageClass" "key"="backup/family-media-bk"
helpers.go:218] "msg"="got StorageClass" "key"="backup/family-media-bk" "name"="fast-ceph-bucket"
controller.go:270] "msg"="syncing obc creation" "key"="backup/family-media-bk"
controller.go:552] "msg"="updating OBC metadata" "key"="backup/family-media-bk"
resourcehandlers.go:277] "msg"="updating" "key"="backup/family-media-bk" "obc"="backup/family-media-bk"
controller.go:341] "msg"="provisioning" "bucket"="family-media-bk" "key"="backup/family-media-bk"
D | op-bucket-prov: Provision event for OB options: &{ReclaimPolicy:0xc007b82390 BucketName:family-media-bk UserID:obc-backup-family-media-bk-XXXXXX-7686-4504-80c1-3a3287bb8976 ObjectBucketClaim:0xc007b90840 Parameters:map[objectStoreName:fast-ceph-objectstore objectStoreNamespace:rook-ceph region:us-east-1]}
I | op-bucket-prov: initializing and setting CreateOrGrant services
I | op-bucket-prov: getting storage class "fast-ceph-bucket"
E | clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
I | ceph-spec: parsing mon endpoints: c=172.XX.XX.XX:6789,h=172.XX.XX.XX:6789,d=172.XX.XX.XX:6789
D | ceph-spec: loaded: maxMonID=7, mons=map[c:0xc007b97380 d:0xc007b973e0 h:0xc007b973b0], assignment=&{Schedule:map[c:0xc0079cde40 d:0xc0079cde80 h:0xc0079cdec0]}
D | CmdReporter: job ceph-file-controller-detect-version has returned results
D | ceph-object-controller: creating s3 user object "rgw-admin-ops-user" for object store "fast-ceph-objectstore"
D | ceph-object-controller: creating s3 user "rgw-admin-ops-user"
D | exec: Running command: radosgw-admin user create --uid rgw-admin-ops-user --display-name RGW Admin Ops User --caps buckets=*;users=*;usage=read;metadata=read;zone=read --rgw-realm=fast-ceph-objectstore --rgw-zonegroup=fast-ceph-objectstore --rgw-zone=fast-ceph-objectstore --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
E | ceph-bucket-notification: failed to reconcile failed to list bucket notifications in ObjectbucketClaim "backup/obc-backup-bang-media-bk": failed to create S3 agent for CephBucketNotification provisioning for bucket "bang-media-bk": failed to get admin Ops context for CephObjectStore "rook-ceph/fast-ceph-objectstore": failed to create or retrieve rgw admin ops user: failed to create object user "rgw-admin-ops-user". error code 1 for object store "fast-ceph-objectstore": skipping reconcile since operator is still initializing
D | ceph-spec: "ceph-bucket-notification-controller": CephCluster resource "rook-ceph" found in namespace "rook-ceph"
D | ceph-spec: "ceph-bucket-notification-controller": ceph status is "HEALTH_WARN", operator is ready to run ceph command, reconciling
D | ceph-object-controller: creating s3 user object "rgw-admin-ops-user" for object store "fast-ceph-objectstore"
D | ceph-object-controller: creating s3 user "rgw-admin-ops-user"
D | exec: Running command: radosgw-admin user create --uid rgw-admin-ops-user --display-name RGW Admin Ops User --caps buckets=*;users=*;usage=read;metadata=read;zone=read --rgw-realm=fast-ceph-objectstore --rgw-zonegroup=fast-ceph-objectstore --rgw-zone=fast-ceph-objectstore --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
controller.go:204] "Unhandled Error" err="error syncing 'backup/family-media-bk': error provisioning bucket: skipping reconcile since operator is still initializing, requeuing" logger="UnhandledError"
```

The mons' IPs are correct.

From 
```
clusterdisruption-controller: failed to get OSD status: failed to get osd metadata: exit status 1
```
I did check the osd by `ceph osd status`. Besides one osd is highly unused, so the cluster is unbalance in that way, nothing special. I heard about changing the weight is only temporary fix this problem, so I just give up. ceph never balance osd by itself. `ceph -s` is the same.

```
failed to get admin Ops context for CephObjectStore "rook-ceph/fast-ceph-objectstore": failed to create or retrieve rgw admin ops user: failed to create object user "rgw-admin-ops-user"
```
rgw-admin-ops-user exists and nothing special by `radosgw-admin user info --uid rgw-admin-ops-user`.

I did back up cephcluster, secret and configmap form rook-ceph namespace. I also did back up 3 nodes' /var/lib/rook directory. These back up is a few days ago. Not sure if it helps. Thanks.

**Comment by BlaineEXE** [comment]
The admin ops user issue looks too familiar. Are you able to upgrade to Rook v1.17.7? We just released a fix for the issue in that release today, and I hope that may help. If we are lucky, that might also resolve the OBC issue, but I'm not certain

Backport PR here for reference: https://github.com/rook/rook/pull/16204

**Comment by grapemix** [comment]
So I have upgraded both rook-ceph-operator and rook-ceph-cluster to v1.17.7.

I saw this msg: `ceph-spec: CephCluster "rook-ceph" status: "Ready". "Cluster created successfully"`. So I will assume the upgrade has been completed and success. My mons' IP are still corrected.

The bucket permission problem still exist unfortunately. The good news the frequency of prompting err has decrease. A few new err has been logged:
```
I | op-bucket-prov: Provision: creating bucket "family-media-bk" for OBC "family-media-bk"
I | op-bucket-prov: creating Ceph object user "obc-backup-family-media-bk-XXXXX-7686-4504-80c1-3a3287bb8976"
I | op-bucket-prov: Ceph object user "obc-backup-family-media-bk-XXXXX-7686-4504-80c1-3a3287bb8976" already exists
I | op-bucket-prov: successfully created Ceph object user "obc-backup-family-media-bk-XXXXX-7686-4504-80c1-3a3287bb8976" with access keys
D | op-bucket-prov: bucket "family-media-bk" already exists and is owned by user "obc-rook-ceph-family-media-bk-XXXXX-6e5a-4f17-a7cb-42c6f04bba2e" instead of user "obc-backup-family-media-bk-XXXXX-7686-4504-80c1-3a3287bb8976", relinking...
I | ceph-bucket-notification: successfully fetched ceph user "obc-backup-family-bk-XXXXX-20b5-4724-864c-c6706ab7422c"
DEBUG: Request s3/GetBucketNotificationConfiguration Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /family-bk?notification= HTTP/1.1
Host: rook-ceph-rgw-fast-ceph-objectstore.rook-ceph.svc
User-Agent: aws-sdk-go/1.55.7 (go1.23.11; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=XXXXX/20250801/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-expected-bucket-owner, Signature=17dc0873da8cc36b786d99e9f81905580aea4d3cc7e675cb1cef4c984f81b543
X-Amz-Content-Sha256: XXXXX
X-Amz-Date: 20250801T002308Z
X-Amz-Expected-Bucket-Owner: obc-backup-family-bk-XXXXX-20b5-4724-864c-c6706ab7422c
Accept-Encoding: gzip
-----------------------------------------------------
I | op-bucket-prov: set user "obc-backup-family-media-bk-XXXXX-7686-4504-80c1-3a3287bb8976" bucket max to 1
D | ceph-bucket-notification: Bucket Notifications [] was listed for bucket "family-bk"
D | ceph-bucket-notification: reconciling ObjectBucketClaim backup/bang-media-bk labels for bucket notifications
DEBUG: Response s3/GetBucketNotificationConfiguration Details:
	
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 55
Connection: Keep-Alive
Content-Type: application/xml
Date: Fri, 01 Aug 2025 00:23:08 GMT
Server: Ceph Object Gateway (squid)
X-Amz-Request-Id: XXXXX-00688c08ec-41228690-fast-ceph-objectstore
-----------------------------------------------------
D | ceph-spec: "ceph-bucket-notification-controller": CephCluster resource "rook-ceph" found in namespace "rook-ceph"
D | ceph-spec: "ceph-bucket-notification-controller": ceph status is "HEALTH_WARN", operator is ready to run ceph command, reconciling
D | ceph-spec: found existing monitor secrets for cluster rook-ceph
I | ceph-spec: parsing mon endpoints: h=172.XX.XX.XX:6789,d=172.XX.XX.XX:6789,c=172.XX.XX.XX:6789
D | ceph-spec: loaded: maxMonID=7, extMons=map[], mons=map[c:0xc004bf2120 d:0xc004bf20f0 h:0xc004bf20c0], assignment=&{Schedule:map[c:0xc00985c4c0 d:0xc00985c500 h:0xc00985c540]}
D | ceph-object-controller: creating s3 user object "rgw-admin-ops-user" for object store "fast-ceph-objectstore"
D | ceph-object-controller: creating s3 user "rgw-admin-ops-user"
D | exec: Running command: radosgw-admin user create --uid rgw-admin-ops-user --display-name RGW Admin Ops User --caps buckets=*;users=*;usage=read;metadata=read;zone=read --rgw-realm=fast-ceph-objectstore --rgw-zonegroup=fast-ceph-objectstore --rgw-zone=fast-ceph-objectstore --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
	
DEBUG: Request s3/GetBucketPolicy Details:
	
---[ REQUEST POST-SIGN ]-----------------------------
GET /family-media-bk?policy= HTTP/1.1
Host: rook-ceph-rgw-fast-ceph-objectstore.rook-ceph.svc
User-Agent: aws-sdk-go/1.55.7 (go1.23.11; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=XXXXX/20250801/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=XXXXX
X-Amz-Content-Sha256: XXXXX
X-Amz-Date: 20250801T002308Z
Accept-Encoding: gzip
-----------------------------------------------------
DEBUG: Response s3/GetBucketPolicy Details:
	
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 Not Found
Content-Length: 332
2025-08-01 00:23:08.378206 D | op-bucket-prov: Policy for bucket "family-media-bk" has changed. diff:  any(
Accept-Ranges: bytes
- 	&(*string)(nil),
+ 	(*string)(nil),
  )
Connection: Keep-Alive
Content-Type: application/xml
Date: Fri, 01 Aug 2025 00:23:08 GMT
Server: Ceph Object Gateway (squid)
X-Amz-Request-Id: XXXXX-00688c08ec-41228690-fast-ceph-objectstore
	
-----------------------------------------------------
DEBUG: Request s3/DeleteBucketPolicy Details:
---[ REQUEST POST-SIGN ]-----------------------------
DELETE /family-media-bk?policy= HTTP/1.1
Host: rook-ceph-rgw-fast-ceph-objectstore.rook-ceph.svc
User-Agent: aws-sdk-go/1.55.7 (go1.23.11; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=XXXXX/20250801/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=XXXXX
X-Amz-Content-Sha256: XXXXX
X-Amz-Date: 20250801T002308Z
Accept-Encoding: gzip
-----------------------------------------------------
DEBUG: Response s3/DeleteBucketPolicy Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 204 No Content
Connection: Keep-Alive
Date: Fri, 01 Aug 2025 00:23:08 GMT
Server: Ceph Object Gateway (squid)
X-Amz-Request-Id: XXXXX-00688c08ec-41228690-fast-ceph-objectstore
-----------------------------------------------------
DEBUG: Request s3/GetBucketLifecycleConfiguration Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /family-media-bk?lifecycle= HTTP/1.1
Host: rook-ceph-rgw-fast-ceph-objectstore.rook-ceph.svc
User-Agent: aws-sdk-go/1.55.7 (go1.23.11; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=XXXXX/20250801/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=XXXXX
X-Amz-Content-Sha256: XXXXX
X-Amz-Date: 20250801T002308Z
Accept-Encoding: gzip
	
-----------------------------------------------------
DEBUG: Response s3/GetBucketLifecycleConfiguration Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 Not Found
2025-08-01 00:23:08.428594 D | op-bucket-prov: no lifecycle configuration set for bucket "family-media-bk"
Content-Length: 310
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Type: application/xml
Date: Fri, 01 Aug 2025 00:23:08 GMT
Server: Ceph Object Gateway (squid)
X-Amz-Request-Id: XXXXX-00688c08ec-41228690-fast-ceph-objectstore
resourcehandlers.go:147] "msg"="creating Secret" "key"="backup/family-media-bk" "name"="backup/family-media-bk"
	
-----------------------------------------------------
resourcehandlers.go:151] "msg"="updating Secret" "key"="backup/family-media-bk" "name"="backup/family-media-bk"
resourcehandlers.go:167] "msg"="creating ConfigMap" "key"="backup/family-media-bk" "name"="backup/family-media-bk"
resourcehandlers.go:171] "msg"="updating ConfigMap" "key"="backup/family-media-bk" "name"="backup/family-media-bk"
helpers.go:107] "msg"="getting claim for key" "key"="backup/family-media-bk"
resourcehandlers.go:116] "msg"="creating ObjectBucket" "key"="backup/family-media-bk" "name"="obc-backup-family-media-bk"
resourcehandlers.go:121] "msg"="updating ObjectBucket" "key"="backup/family-media-bk" "name"="obc-backup-family-media-bk"
resourcehandlers.go:277] "msg"="updating" "key"="backup/family-media-bk" "obc"="backup/family-media-bk"
resourcehandlers.go:287] "msg"="updating status:" "key"="backup/family-media-bk" "new status"="Bound" "obc"="backup/family-media-bk" "old status"="Bound"

---[ REQUEST POST-SIGN ]-----------------------------
GET /family-media-bk?notification= HTTP/1.1
Host: rook-ceph-rgw-fast-ceph-objectstore.rook-ceph.svc
User-Agent: aws-sdk-go/1.55.7 (go1.23.11; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=XXXXX/20250801/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-expected-bucket-owner, Signature=XXXXX
X-Amz-Content-Sha256: XXXXX
X-Amz-Date: 20250801T002921Z
X-Amz-Expected-Bucket-Owner: obc-rook-ceph-family-media-bk-XXXXX-6e5a-4f17-a7cb-42c6f04bba2e
Accept-Encoding: gzip
-----------------------------------------------------
DEBUG: Response s3/GetBucketNotificationConfiguration Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403 Forbidden
Content-Length: 294
Accept-Ranges: bytes
E | ceph-bucket-notification: failed to reconcile failed to list bucket notifications in ObjectbucketClaim "rook-ceph/obc-rook-ceph-family-media-bk": failed to get BucketNotification from bucket "family-media-bk": AccessDenied: 
    status code: 403, request id: XXXXX-fast-ceph-objectstore, host id: 
Connection: Keep-Alive
Content-Type: application/xml
Date: Fri, 01 Aug 2025 00:29:21 GMT
Server: Ceph Object Gateway (squid)
X-Amz-Request-Id: XXXXX-fast-ceph-objectstore
-----------------------------------------------------
```
A few observations:
1. ceph operator relinks the two users. Both users still exist in `radosgw-admin user list`. Bucket's owner is still the acct ends with 3a3287bb8976.
2. If GetBucketNotificationConfiguration of family-media-bk doesn't return 403, I will assume the permission problem is gone. Now I am not sure. May be it is because DeleteBucketPolicy has been called?
3. Some buckets like family-bk (different name) 's GetBucketNotificationConfiguration call return 200.
4. GetBucketLifecycleConfiguration of family-media-bk returns 404, so one more information is reported missing.

I hope this log helps. Thx.

**Comment by BlaineEXE** [comment]
I think the bucket policy diff looks like it could have a small bug. I opened a tangential issue here: https://github.com/rook/rook/issues/16219

Still, I don't think that is the source of the issue here.

**Comment by BlaineEXE** [comment]
> Some buckets like family-bk (different name) 's GetBucketNotificationConfiguration call return 200.
GetBucketLifecycleConfiguration of family-media-bk returns 404, so one more information is reported missing.

This is confusing to me. It's helpful for debugging to know that other buckets can be successfully queried. But I am having a hard time guessing about why this particular user isn't getting queried correctly. My vague guess is that RGW may have some odd corner case in the metadata for this particular bucket/user, but I'm not sure.

It would be helfpul if you could use `radosgw-admin` to get info from one of the working buckets to compare to this non-working bucket. And ditto for both buckets' users. If you could pinpoint any differences, that could help debug further.

I wish I had more specific to go on right now for you. Thanks for the patience

**Comment by jhoblitt** [comment]
@grapemix Here is the code that generates the name for the rgw user for v1.15.7, v1.16.8, and v1.17.7:

- https://github.com/rook/rook/blob/v1.15.7/pkg/operator/ceph/object/bucket/rgw-handlers.go#L58
- https://github.com/rook/rook/blob/v1.16.8/pkg/operator/ceph/object/bucket/rgw-handlers.go#L58
- https://github.com/rook/rook/blob/v1.17.7/pkg/operator/ceph/object/bucket/rgw-handlers.go#L104

It is `	return "obc-" + obc.Namespace + "-" + obc.Name + "-" + string(obc.UID)` for all 3 releases.

Is it possible that there are obc's in both the `backup` and `rook-ceph` ns?

This error message is from the operator trying to sync an obc in the `rook-ceph` ns:

```
E | ceph-bucket-notification: failed to reconcile failed to list bucket notifications in ObjectbucketClaim "rook-ceph/obc-rook-ceph-family-media-bk": failed to get BucketNotification from bucket "family-media-bk": AccessDenied: 
```

An http 403 is expected when trying to query the configured bucket notifications with credentials for a different user than owns the bucket: https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketNotificationConfiguration.html

The error messages are suggestive that there are obc's in two different namespaces trying to manage the same bucket name.

**Comment by grapemix** [comment]
> Is it possible that there are obc's in both the backup and rook-ceph ns?
Jackpot. You are right. 
```
kubectl get obc -A |grep family-media-bk
backup       family-media-bk   336d
rook-ceph    family-media-bk   2d17h
```
Namespace rook-ceph is added to kustomization.yaml from a git merge. If namespace is defined in kustomization.yaml, the namespace in kustomization.yaml will override the namespace defined in the OBC object and hence new OBC with exact name is created in rook-ceph. My IaC blind spot make me only checking the file change of OBC's YAML and describing OBC for the error events instead of listing OBC. My bad.

After deleting OBC from rook-ceph, everything seems fine now.

I am terrible sorry for all your time.


PS: For those who wonder why I choose to upgrade rook right after change my mons' IP or why do I even want to change mons' IP, upgrading cilium + switch to gateway API can be a mess. My rook's CSI fell in crashloop. I am not sure if the root cause is from my rook's setup or cilium's setup. That's why I have to change my whole network's setup including mons' IP for cilium. And that's why I upgrade rook to see if I can fix rook's CSI pods. Anyway, my rook's CSI plugins go back to work now. But troubleshooting multiple components all at once is no fun.

**Comment by BlaineEXE** [comment]
I'm glad we were able to find a solution for you. Thanks for letting us know the resolution as well. This will be helpful for any users who might hit the same issue in the future
