### ISSUE TITLE
agent pod: `/usr/libexec/kubernetes: read-only file system`

### ISSUE THREAD

**Issue by hongkailiu** [rook/rook#2612]
**Is this a bug report or feature request?**
* Bug Report

```
~/go/src/github.com/rook/rook/cluster/examples/kubernetes/ceph # git log --oneline -1
28ebec1 Merge pull request #2609 from dyusupov/master
# git diff
diff --git a/cluster/examples/kubernetes/ceph/operator.yaml b/cluster/examples/kubernetes/ceph/operator.yaml
index 73cde2e..ba4bab8 100755
--- a/cluster/examples/kubernetes/ceph/operator.yaml
+++ b/cluster/examples/kubernetes/ceph/operator.yaml
@@ -469,7 +469,7 @@ spec:
         # This is necessary to workaround the anyuid issues when running on OpenShift.
         # For more details see https://github.com/rook/rook/issues/1314#issuecomment-355799641
         - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
-          value: "false"
+          value: "true"
         # In some situations SELinux relabelling breaks (times out) on large filesystems, and doesn't work with cephfs Rea
         # Disable it here if you have similiar issues.
         # For more details see https://github.com/rook/rook/issues/2417


# oc create -f scc.yaml
# oc create -f operator.yaml

# oc get pod -n rook-ceph-system
NAME                                 READY   STATUS                 RESTARTS   AGE
rook-ceph-agent-6mvrd                0/1     CreateContainerError   0          29m
rook-ceph-agent-lrl8t                0/1     CreateContainerError   0          29m
rook-ceph-agent-x6b94                0/1     CreateContainerError   0          29m
rook-ceph-operator-765b9f645-t68vz   1/1     Running                0          30m
rook-discover-27fwl                  1/1     Running                0          29m
rook-discover-88nsq                  1/1     Running                0          29m
rook-discover-x9nnc                  1/1     Running                0          29m

# oc describe pod -n rook-ceph-system rook-ceph-agent-6mvrd
Name:               rook-ceph-agent-6mvrd
Namespace:          rook-ceph-system
Priority:           0
PriorityClassName:  <none>
Node:               ip-10-0-130-150.us-east-2.compute.internal/10.0.130.150
Start Time:         Mon, 04 Feb 2019 19:59:24 +0000
Labels:             app=rook-ceph-agent
                    controller-revision-hash=6ffd9f95f4
                    pod-template-generation=1
Annotations:        openshift.io/scc: rook-ceph
Status:             Pending
IP:                 10.0.130.150
Controlled By:      DaemonSet/rook-ceph-agent
Containers:
  rook-ceph-agent:
    Container ID:  
    Image:         rook/ceph:master
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      ceph
      agent
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Environment:
      POD_NAMESPACE:                   rook-ceph-system (v1:metadata.namespace)
      NODE_NAME:                        (v1:spec.nodeName)
      AGENT_MOUNT_SECURITY_MODE:       Any
      ROOK_ENABLE_SELINUX_RELABELING:  true
      ROOK_ENABLE_FSGROUP:             true
    Mounts:
      /dev from dev (rw)
      /flexmnt from flexvolume (rw)
      /lib/modules from libmodules (rw)
      /sys from sys (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-system-token-cbsj5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  flexvolume:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
    HostPathType:  
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  
  libmodules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  rook-ceph-system-token-cbsj5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-system-token-cbsj5
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                   From                                                 Message
  ----     ------     ----                  ----                                                 -------
  Normal   Scheduled  30m                   default-scheduler                                    Successfully assigned rook-ceph-system/rook-ceph-agent-6mvrd to ip-10-0-130-150.us-east-2.compute.internal
  Normal   Pulling    30m                   kubelet, ip-10-0-130-150.us-east-2.compute.internal  pulling image "rook/ceph:master"
  Normal   Pulled     29m                   kubelet, ip-10-0-130-150.us-east-2.compute.internal  Successfully pulled image "rook/ceph:master"
  Warning  Failed     27m (x12 over 29m)    kubelet, ip-10-0-130-150.us-east-2.compute.internal  Error: Failed to mkdir /usr/libexec/kubernetes/kubelet-plugins/volume/exec: mkdir /usr/libexec/kubernetes: read-only file system
  Normal   Pulled     5m2s (x115 over 29m)  kubelet, ip-10-0-130-150.us-east-2.compute.internal  Container image "rook/ceph:master" already present on machine


```

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**Environment**:
```
# oc get clusterversion version -o json | jq -r .status.desired
{
  "image": "registry.svc.ci.openshift.org/ocp/release@sha256:d03ce0ef85540a1fff8bfc1c408253404aaecb2b958d7c3f24896f3597c3715b",
  "version": "4.0.0-0.nightly-2019-01-30-145955"
}
```

* OS (e.g. from /etc/os-release):
```
$ cat /etc/*release
NAME="Red Hat CoreOS"
VERSION="4.0"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION_ID="4.0"
PRETTY_NAME="Red Hat CoreOS 4.0"
ANSI_COLOR="0;31"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat 7"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.0"
REDHAT_SUPPORT_PRODUCT="Red Hat"
REDHAT_SUPPORT_PRODUCT_VERSION="4.0"
OSTREE_VERSION=47.300
Red Hat CoreOS release 4.0
Red Hat CoreOS release 4.0

$ uname -a
Linux ip-10-0-18-200 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

# kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4+f39ab668d3", GitCommit:"f39ab668d3", GitTreeState:"clean", BuildDate:"2019-01-29T23:38:27Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4+f39ab668d3", GitCommit:"f39ab668d3", GitTreeState:"clean", BuildDate:"2019-01-29T23:36:59Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}


```
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by hongkailiu** [comment]
Also ssh to one of the node, I cannot create that folder either manually.

```
[root@ip-10-0-18-200 ~]# mkdir -p /usr/libexec/kubernetes
mkdir: cannot create directory ‘/usr/libexec/kubernetes’: Read-only file system

[root@ip-10-0-18-200 /]# ls -alrt
total 16
drwxr-xr-x.  12 root root  155 Jan  1  1970 usr
drwxr-xr-x.  11 root root  112 Feb  3 17:20 sysroot
lrwxrwxrwx.   2 root root    7 Feb  3 17:20 bin -> usr/bin
lrwxrwxrwx.   2 root root    7 Feb  3 17:20 lib -> usr/lib
lrwxrwxrwx.   2 root root    9 Feb  3 17:20 media -> run/media
lrwxrwxrwx.   2 root root    8 Feb  3 17:20 home -> var/home
lrwxrwxrwx.   2 root root    7 Feb  3 17:20 mnt -> var/mnt
lrwxrwxrwx.   2 root root    9 Feb  3 17:20 lib64 -> usr/lib64
lrwxrwxrwx.   2 root root    8 Feb  3 17:20 sbin -> usr/sbin
lrwxrwxrwx.   2 root root   12 Feb  3 17:20 root -> var/roothome
lrwxrwxrwx.   2 root root   14 Feb  3 17:20 ostree -> sysroot/ostree
lrwxrwxrwx.   2 root root    7 Feb  3 17:20 opt -> var/opt
lrwxrwxrwx.   2 root root    7 Feb  3 17:20 srv -> var/srv
drwxr-xr-x.  12 root root  253 Feb  3 17:21 ..
drwxr-xr-x.  12 root root  253 Feb  3 17:21 .
drwxr-xr-x.  23 root root 4096 Feb  4 13:25 var
drwxr-xr-x.   5 root root   63 Feb  4 13:25 boot
dr-xr-xr-x. 258 root root    0 Feb  4 19:53 proc
dr-xr-xr-x.  13 root root    0 Feb  4 19:53 sys
drwxr-xr-x.  16 root root 2860 Feb  4 19:53 dev
drwxr-xr-x.  38 root root 1020 Feb  4 19:53 run
drwxrwxrwt.   8 root root  240 Feb  4 20:23 tmp
drwxr-xr-x.  82 root root 8192 Feb  4 20:54 etc
```

**Comment by travisn** [comment]
You're on OCP 4.0? This sounds related to flex being broken on 4.0 as well, although I don't see any details on that issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1667606

**Comment by hongkailiu** [comment]
@travisn Thanks for the reply.
Yes, I am on OCP 4.0.
I will watch that bug and give it another try when we have a version with fix.

**Comment by JohnStrunk** [comment]
The host dir for flex had to be changed to a writable location in RHCOS. Hemant owns the related Jira ticket.

**Comment by ksingh7** [comment]
Hitting the exact same issue with OCP 4.0

**Comment by ksingh7** [comment]
@JohnStrunk  is there a way I can apply this as a hotfix to my existing OCP 4.0 cluster? If yes can you give me some pointers on how to do that?

I have deployed my cluster using 

```
$ ./openshift-install-darwin-amd64 version
./openshift-install-darwin-amd64 v0.12.0
```

**Comment by gnufied** [comment]
I somehow missed this issue. Sorry about it.  I have updated the BZ - https://bugzilla.redhat.com/show_bug.cgi?id=1667606 with some more details.

Basically, `/etc/kubernetes/kubelet-plugins/volume/exec` is new location for flexvolume plugins in RHCOS.  Kubelet, apiserver and controller-manager has been configured with this location.

**Comment by gnufied** [comment]
You can verify that kubelet and controller-manager is using this location by inspecting their configuration on the nodes.

**Comment by hongkailiu** [comment]
I used the latest OCP 4.0 build. The problem is still there.

```
# oc get clusterversion version -o json | jq -r .status.desired
{
  "image": "registry.svc.ci.openshift.org/ocp/release@sha256:7bd57da7777e65f6cd4c8aa726b90ab00b6804ce97819cc83093bf9a1841e32b",
  "version": "4.0.0-0.nightly-2019-02-12-150919"
}
root@ip-172-31-61-110: ~/go/src/github.com/rook/rook/cluster/examples/kubernetes/ceph # oc describe pod -n rook-ceph-system rook-ceph-agent-5k76h
Name:               rook-ceph-agent-5k76h
Namespace:          rook-ceph-system
Priority:           0
PriorityClassName:  <none>
Node:               ip-10-0-173-115.us-east-2.compute.internal/10.0.173.115
Start Time:         Tue, 12 Feb 2019 20:27:25 +0000
Labels:             app=rook-ceph-agent
                    controller-revision-hash=58f8dbd95c
                    pod-template-generation=1
Annotations:        openshift.io/scc: rook-ceph
Status:             Pending
...
Events:
  Type     Reason     Age                   From                                                 Message
  ----     ------     ----                  ----                                                 -------
  Normal   Scheduled  32m                   default-scheduler                                    Successfully assigned rook-ceph-system/rook-ceph-agent-5k76h to ip-10-0-173-115.us-east-2.compute.internal
  Warning  Failed     29m (x12 over 32m)    kubelet, ip-10-0-173-115.us-east-2.compute.internal  Error: Failed to mkdir /usr/libexec/kubernetes/kubelet-plugins/volume/exec: mkdir /usr/libexec/kubernetes: read-only file system
  Normal   Pulled     118s (x142 over 32m)  kubelet, ip-10-0-173-115.us-east-2.compute.internal  Container image "rook/ceph:v0.9.2" already present on machine
```

Seems the new location is picked by k8s but somehow rook does not. @gnufied let me know what I missed.

```
# grep -irn "volume-p" /etc/kubernetes/
/etc/kubernetes/static-pod-resources/kube-controller-manager-pod-2/configmaps/config/config.yaml:1:{"apiVersion":"kubecontrolplane.config.openshift.io/v1","extendedArguments":{"allocate-node-cidrs":["true"],"cloud-provider":["aws"],"cluster-cidr":["10.128.0.0/14"],"cluster-signing-cert-file":["/etc/kubernetes/static-pod-resources/secrets/csr-signer/tls.crt"],"cluster-signing-key-file":["/etc/kubernetes/static-pod-resources/secrets/csr-signer/tls.key"],"configure-cloud-routes":["false"],"controllers":["*","-ttl","-bootstrapsigner","-tokencleaner"],"enable-dynamic-provisioning":["true"],"experimental-cluster-signing-duration":["720h"],"feature-gates":["PersistentLocalVolumes=false"],"flex-volume-plugin-dir":["/etc/kubernetes/kubelet-plugins/volume/exec"],"kube-api-burst":["300"],"kube-api-qps":["150"],"leader-elect":["true"],"leader-elect-resource-lock":["configmaps"],"leader-elect-retry-period":["3s"],"node-monitor-grace-period":["5m"],"pod-eviction-timeout":["5m"],"port":["0"],"root-ca-file":["/etc/kubernetes/static-pod-resources/configmaps/serviceaccount-ca/ca-bundle.crt"],"secure-port":["10257"],"service-account-private-key-file":["/etc/kubernetes/static-pod-resources/secrets/service-account-private-key/service-account.key"],"service-cluster-ip-range":["172.30.0.0/16"],"use-service-account-credentials":["true"]},"kind":"KubeControllerManagerConfig"}
/etc/kubernetes/static-pod-resources/kube-controller-manager-pod-3/configmaps/config/config.yaml:1:{"apiVersion":"kubecontrolplane.config.openshift.io/v1","extendedArguments":{"allocate-node-cidrs":["true"],"cloud-provider":["aws"],"cluster-cidr":["10.128.0.0/14"],"cluster-signing-cert-file":["/etc/kubernetes/static-pod-resources/secrets/csr-signer/tls.crt"],"cluster-signing-key-file":["/etc/kubernetes/static-pod-resources/secrets/csr-signer/tls.key"],"configure-cloud-routes":["false"],"controllers":["*","-ttl","-bootstrapsigner","-tokencleaner"],"enable-dynamic-provisioning":["true"],"experimental-cluster-signing-duration":["720h"],"feature-gates":["PersistentLocalVolumes=false"],"flex-volume-plugin-dir":["/etc/kubernetes/kubelet-plugins/volume/exec"],"kube-api-burst":["300"],"kube-api-qps":["150"],"leader-elect":["true"],"leader-elect-resource-lock":["configmaps"],"leader-elect-retry-period":["3s"],"node-monitor-grace-period":["5m"],"pod-eviction-timeout":["5m"],"port":["0"],"root-ca-file":["/etc/kubernetes/static-pod-resources/configmaps/serviceaccount-ca/ca-bundle.crt"],"secure-port":["10257"],"service-account-private-key-file":["/etc/kubernetes/static-pod-resources/secrets/service-account-private-key/service-account.key"],"service-cluster-ip-range":["172.30.0.0/16"],"use-service-account-credentials":["true"]},"kind":"KubeControllerManagerConfig"}


```

**Comment by gnufied** [comment]
@hongkailiu yeah it looks like, rook is still trying to install the flexvolume plugin in old location. This has to be fixed by rook or rook configuration, so as it can pick updated location.

**Comment by hongkailiu** [comment]
@travisn Can you help to proceed? Thanks.

**Comment by travisn** [comment]
@hongkailiu Can you try setting the `FLEXVOLUME_DIR_PATH` in operator.yaml? See the [flexvolume config](https://rook.io/docs/rook/v0.9/flexvolume.html) topic for more details.

**Comment by hongkailiu** [comment]
@travisn cool. Thanks.
How did I miss it. Stupid me.

**Comment by travisn** [comment]
No worries, there are too many details like this buried in the docs. If only K8s would let us detect this...

**Comment by hongkailiu** [comment]
oh yeah!

```
# oc get pod -n rook-ceph-system
NAME                                  READY   STATUS    RESTARTS   AGE
rook-ceph-agent-bgtrt                 1/1     Running   0          39s
rook-ceph-agent-gcw8k                 1/1     Running   0          39s
rook-ceph-agent-h6bvl                 1/1     Running   0          39s
rook-ceph-operator-769d6854b9-tdtdv   1/1     Running   0          61s
rook-discover-9t8s4                   1/1     Running   0          39s
rook-discover-klgrm                   1/1     Running   0          39s
rook-discover-s2spl                   1/1     Running   0          39s

# oc get clusterversion version -o json | jq -r .status.desired
{
  "image": "registry.svc.ci.openshift.org/ocp/release@sha256:7bd57da7777e65f6cd4c8aa726b90ab00b6804ce97819cc83093bf9a1841e32b",
  "version": "4.0.0-0.nightly-2019-02-12-150919"
}

# git diff operator.yaml
-        # - name: FLEXVOLUME_DIR_PATH
-        #  value: "<PathToFlexVolumes>"
+        - name: FLEXVOLUME_DIR_PATH
+          value: "/etc/kubernetes/kubelet-plugins/volume/exec"
...
         - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
-          value: "false"
+          value: "true"
...

```
