### ISSUE TITLE
configuring osd dirs: map[ceph-storage-dir -1]

### ISSUE THREAD

**Issue by zhangxingdeppon** [rook/rook#3390]
**Is this a bug report or feature request?**
* Bug Report
Good afternoon,buddy,I have faced a problem about rook ceph ,can you help me?
**Deviation from expected behavior:**
I want to add storage node,but rook-ceph-osd-prepare always running not Completed
The situation is as follows

![image](https://user-images.githubusercontent.com/16789841/60653769-42c7c600-9e7d-11e9-9b3b-98e1f10204f0.png)

 the logs for the osd prepare pod：
<pre><code>
[root@D21114U24-61-149 ~]# kubectl logs -f  rook-ceph-osd-prepare-d21112u04-61-142-d7w9q  -n rook-ceph   -c provision
2019-07-04 07:55:46.903699 I | cephcmd: desired devices to configure osds: [{Name: OSDsPerDevice:1 IsFilter:false}]
2019-07-04 07:55:46.906119 I | rookcmd: starting Rook v0.9.0-190.g818bf38 with arguments '/rook/rook ceph osd provision'
2019-07-04 07:55:46.906140 I | rookcmd: flag values: --cluster-id=a2d311a2-5fec-11e9-be46-0894ef05c4c0, --data-device-filter=, --data-devices=, --data-directories=/data2/ceph-storage-dir,/data3/ceph-storage-dir, --encrypted-device=false, --force-format=false, --help=false, --location=, --log-flush-frequency=5s, --log-level=INFO, --metadata-device=, --node-name=d21112u04-61-142, --osd-database-size=20480, --osd-journal-size=5120, --osd-store=, --osd-wal-size=576, --osds-per-device=1
2019-07-04 07:55:46.906157 I | op-mon: parsing mon endpoints: e=10.106.108.210:6789,c=10.99.93.47:6789,d=10.109.95.194:6789
2019-07-04 07:55:46.931520 W | cephconfig: failed to add config file override from '/etc/rook/config/override.conf': open /etc/rook/config/override.conf: no such file or directory
2019-07-04 07:55:46.931547 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2019-07-04 07:55:46.931692 I | cephconfig: copying config to /etc/ceph/ceph.conf
2019-07-04 07:55:46.931805 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
2019-07-04 07:55:46.931812 I | cephosd: discovering hardware
2019-07-04 07:55:46.931825 I | exec: Running command: lsblk --all --noheadings --list --output KNAME
2019-07-04 07:55:46.944782 I | exec: Running command: lsblk /dev/sda --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2019-07-04 07:55:46.946687 W | inventory: skipping device sda: Failed to complete 'lsblk /dev/sda': exit status 1. lsblk: /dev/sda: not a block device
2019-07-04 07:55:46.946708 I | exec: Running command: lsblk /dev/sda1 --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2019-07-04 07:55:46.948708 W | inventory: skipping device sda1: Failed to complete 'lsblk /dev/sda1': exit status 1. lsblk: /dev/sda1: not a block device
2019-07-04 07:55:46.948728 I | exec: Running command: lsblk /dev/sda2 --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2019-07-04 07:55:46.950443 W | inventory: skipping device sda2: Failed to complete 'lsblk /dev/sda2': exit status 1. lsblk: /dev/sda2: not a block device
2019-07-04 07:55:46.950468 I | exec: Running command: lsblk /dev/sda3 --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2019-07-04 07:55:46.952288 W | inventory: skipping device sda3: Failed to complete 'lsblk /dev/sda3': exit status 1. lsblk: /dev/sda3: not a block device
2019-07-04 07:55:46.952315 I | exec: Running command: lsblk /dev/sdb --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2019-07-04 07:55:46.954203 W | inventory: skipping device sdb: Failed to complete 'lsblk /dev/sdb': exit status 1. lsblk: /dev/sdb: not a block device
2019-07-04 07:55:46.954220 I | exec: Running command: lsblk /dev/sdc --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2019-07-04 07:55:46.955677 W | inventory: skipping device sdc: Failed to complete 'lsblk /dev/sdc': exit status 1. lsblk: /dev/sdc: not a block device
2019-07-04 07:55:46.955695 I | exec: Running command: lsblk /dev/sdd --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2019-07-04 07:55:46.957334 W | inventory: skipping device sdd: Failed to complete 'lsblk /dev/sdd': exit status 1. lsblk: /dev/sdd: not a block device
2019-07-04 07:55:46.957352 I | exec: Running command: lsblk /dev/sde --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2019-07-04 07:55:46.959061 W | inventory: skipping device sde: Failed to complete 'lsblk /dev/sde': exit status 1. lsblk: /dev/sde: not a block device
2019-07-04 07:55:46.959080 I | exec: Running command: lsblk /dev/sdf --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2019-07-04 07:55:46.960577 W | inventory: skipping device sdf: Failed to complete 'lsblk /dev/sdf': exit status 1. lsblk: /dev/sdf: not a block device
2019-07-04 07:55:46.960593 I | exec: Running command: lsblk /dev/sdg --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2019-07-04 07:55:46.962067 W | inventory: skipping device sdg: Failed to complete 'lsblk /dev/sdg': exit status 1. lsblk: /dev/sdg: not a block device
2019-07-04 07:55:46.962088 I | exec: Running command: lsblk /dev/sdh --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2019-07-04 07:55:46.963583 W | inventory: skipping device sdh: Failed to complete 'lsblk /dev/sdh': exit status 1. lsblk: /dev/sdh: not a block device
2019-07-04 07:55:46.963600 I | cephosd: creating and starting the osds
2019-07-04 07:55:46.969498 I | cephosd: configuring osd devices: {"Entries":{}}
2019-07-04 07:55:46.969523 I | exec: Running command: ceph-volume lvm batch --prepare
2019-07-04 07:55:47.093140 I | cephosd: no more devices to configure
2019-07-04 07:55:47.093189 I | exec: Running command: ceph-volume lvm list --format json
2019-07-04 07:55:47.255481 I | cephosd: 0 ceph-volume osd devices configured on this node
2019-07-04 07:55:47.255522 I | cephosd: devices = []
2019-07-04 07:55:47.258528 I | cephosd: configuring osd dirs: map[/data2/ceph-storage-dir:-1 /data3/ceph-storage-dir:-1]
2019-07-04 07:55:47.258790 I | exec: Running command: ceph osd create 800da16e-0a2f-4f96-bf7d-3893769d6caf --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/158193659
</code></pre>
**Expected behavior:**
why do the logs show "configuring osd dirs: map[/data2/ceph-storage-dir:-1 /data3/ceph-storage-dir:-1]" ?
I have no idea for this problem,If need me show more details about the failure,I can provide it，please help me resolve it, thanks very much.
**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
sh-4.2# ceph version
ceph version 13.2.4 (b10be4d44915a4d78a8e06aa31919e74927b142e) mimic (stable)
<pre><code>
[root@D21114U24-61-149 ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
</code></pre>

**Comment by leseb** [comment]
Can you paste your cluster CR?

**Comment by zhangxingdeppon** [comment]
> Can you paste your cluster CR?
I'm sorry,I don't known the meaning “CR”,I guess it means "cluster  status" ,
<pre><code>
[root@D21114U24-61-149 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"
</code></pre>
<pre><code>
sh-4.2# ceph version
ceph version 13.2.4 (b10be4d44915a4d78a8e06aa31919e74927b142e) mimic (stable)
</code></pre>

rook ceph operater status below:
![image](https://user-images.githubusercontent.com/16789841/60665574-67c93280-9e97-11e9-86cc-b71630fae29e.png)

ceph status below:

![image](https://user-images.githubusercontent.com/16789841/60665615-87f8f180-9e97-11e9-8a36-f1ea7d0117dd.png)

![image](https://user-images.githubusercontent.com/16789841/60665656-aa8b0a80-9e97-11e9-8c3b-3c10f072ccb5.png)

Is the answer you want?if not，please tell me，i will show it，thanks.

**Comment by leseb** [comment]
Cr = Custom Ressource, the yaml file you used to create your cluster. Thanks.

**Comment by zhangxingdeppon** [comment]
> Cr = Custom Ressource, the yaml file you used to create your cluster. Thanks.

ok,I got it. 
this is my yaml file.

<pre><code>
[root@D21114U24-61-149 ceph]# cat cluster.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-osd
  namespace: rook-ceph
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-osd
  namespace: rook-ceph
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
---
# Aspects of ceph-mgr that require access to the system namespace
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-system
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
# Aspects of ceph-mgr that operate within the cluster's namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ceph.rook.io
  resources:
  - "*"
  verbs:
  - "*"
---
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster-mgmt
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph-system
---
# Allow the osd pods in this namespace to work with configmaps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-osd
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-osd
subjects:
- kind: ServiceAccount
  name: rook-ceph-osd
  namespace: rook-ceph
---
# Allow the ceph mgr to access the cluster-specific resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-mgr
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
---
# Allow the ceph mgr to access the rook system resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-system
  namespace: rook-ceph-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-system
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
---
# Allow the ceph mgr to access cluster-wide resources necessary for the mgr modules
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-cluster
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # The container image used to launch the Ceph daemon pods (mon, mgr, osd, mds, rgw).
    # v12 is luminous, v13 is mimic, and v14 is nautilus.
    # RECOMMENDATION: In production, use a specific version tag instead of the general v13 flag, which pulls the latest release and could result in different
    # versions running within the cluster. See tags available at https://hub.docker.com/r/ceph/ceph/tags/.
    #image: ceph/ceph:v13
    image: 172.29.62.9:8080/aipaas/ceph/ceph:v13
    # Whether to allow unsupported versions of Ceph. Currently only luminous and mimic are supported.
    # After nautilus is released, Rook will be updated to support nautilus.
    # Do not set to true in production.
    allowUnsupported: false
  # The path on the host where configuration files will be persisted. Must be specified.
  # Important: if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster.
  # In Minikube, the '/data' directory is configured to persist across reboots. Use "/data/rook" in Minikube environment.
  dataDirHostPath: /var/lib/rook
  # set the amount of mons to be started
  mon:
    count: 3
    allowMultiplePerNode: true
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    # port: 8443
    # serve the dashboard using SSL
    # ssl: true
  network:
    # toggle to use hostNetwork
    hostNetwork: false
  rbdMirroring:
    # The number of daemons that will perform the rbd mirroring.
    # rbd mirroring must be configured with "rbd mirror" from the rook toolbox.
    workers: 0
  # To control where various services will be scheduled by kubernetes, use the placement configuration sections below.
  # The example under 'all' would have all services scheduled on kubernetes nodes labeled with 'role=storage-node' and
  # tolerate taints with a key of 'storage-node'.
  placement:
#    all:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#          - matchExpressions:
#            - key: role
#              operator: In
#              values:
#              - storage-node
#      podAffinity:
#      podAntiAffinity:
#      tolerations:
#      - key: storage-node
#        operator: Exists
# The above placement information can also be specified for mon, osd, and mgr components
#    mon:
#    osd:
#    mgr:
    mon:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph-mon
              operator: In
              values:
              - enabled
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph-osd
              operator: In
              values:
              - enabled
    mgr:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: ceph-mgr
              operator: In
              values:
              - enabled
  resources:
# The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
#    mgr:
#      limits:
#        cpu: "500m"
#        memory: "1024Mi"
#      requests:
#        cpu: "500m"
#        memory: "1024Mi"
# The above example requests/limits can also be added to the mon and osd components
#    mon:
#    osd:
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    config:
      # The default and recommended storeType is dynamically set to bluestore for devices and filestore for directories.
      # Set the storeType explicitly only if it is required not to use the default.
      # storeType: bluestore
      #storeType: bluestore
      #databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      #journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1" # this value can be overridden at the node or device level
# Cluster level list of directories to use for storage. These values will be set for all nodes that have no `directories` set.
    #directories:
    # By default create a osd in the dataDirHostPath directory. This should be removed for
    # environments where nodes have disks available for Rook to use.
    #- path: /var/lib/rook
# Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
# nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
    nodes:
#    - name: "d21117u04-62-64"
#      directories: # specific directories to use for storage can be specified for each node
#      - path: "/data/ceph-storage-dir"
#      resources:
#        limits:
#          cpu: "500m"
#          memory: "1024Mi"
#        requests:
#          cpu: "500m"
#          memory: "1024Mi"
##########################################
#    - name: "hostname=d21117u07-62-65"
#      directories: # specific directories to use for storage can be specified for each node
#      - path: "/data/ceph-storage-dir"
#      resources:
#        limits:
#          cpu: "500m"
#          memory: "1024Mi"
#        requests:
#          cpu: "500m"
#          memory: "1024Mi"
#############################################
#    - name: "d21117u10-62-66"
#      directories: # specific directories to use for storage can be specified for each node
#      - path: "/data/ceph-storage-dir"
#      resources:
#        limits:
#          cpu: "500m"
#          memory: "1024Mi"
#        requests:
#          cpu: "500m"
#          memory: "1024Mi"
################################################
#    nodes:
#    - name: "d21117u13-62-67"
#      directories: # specific directories to use for storage can be specified for each node
#      - path: "/data/ceph-storage-dir"
#      resources:
#        limits:
#          cpu: "500m"
#          memory: "1024Mi"
#        requests:
#          cpu: "500m"
#          memory: "1024Mi"
################################################
#    - name: "d21117u16-62-68"
#      directories: # specific directories to use for storage can be specified for each node
#      - path: "/data/ceph-storage-dir"
#      resources:
#        limits:
#          cpu: "500m"
#          memory: "1024Mi"
#        requests:
#          cpu: "500m"
#          memory: "1024Mi"
###############################################
    - name: "d21012u11-62-94"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/nvmedata/ceph-storage-dir"
      resources:
        limits:
          cpu: "2"
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
##############################################
    - name: "d21013u04-62-95"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/nvmedata/ceph-storage-dir"
      resources:
        limits:
          cpu: "2" 
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
##############################################
    - name: "d21013u11-62-96"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/nvmedata/ceph-storage-dir"
      resources:
        limits:
          cpu: "2"
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
###############################################
    - name: "d21014u04-62-97"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/nvmedata/ceph-storage-dir"
      resources:
        limits:
          cpu: "2"
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
###############################################
    - name: "d21014u11-62-98"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/nvmedata/ceph-storage-dir"
      resources:
        limits:
          cpu: "2"
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
###############################################
    - name: "d21015u04-62-99"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/nvmedata/ceph-storage-dir"
      resources:
        limits:
          cpu: "2"
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
###############################################
    - name: "d21015u11-62-100"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/nvmedata/ceph-storage-dir"
      resources:
        limits:
          cpu: "2"
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
###############################################
    - name: "d21016u04-62-101"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/nvmedata/ceph-storage-dir"
      resources:
        limits:
          cpu: "2"
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"

###############################################
    - name: "d21112u04-61-142"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/data2/ceph-storage-dir"
      - path: "/data3/ceph-storage-dir"
      resources:
        limits:
          cpu: "2"
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
 ###############################################
    - name: "d21112u04-61-143"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/data2/ceph-storage-dir"
#      - path: "/data3/ceph-storage-dir"
      resources:
        limits:
          cpu: "2"
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
###############################################    
    - name: "d2111334u-61-147"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/data2/ceph-storage-dir"
      resources:
        limits:
          cpu: "2"
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"


############################################### 
    - name: "d21114u24-61-148"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/data2/ceph-storage-dir"
      - path: "/data3/ceph-storage-dir"
      resources:
        limits:
          cpu: "2"
          memory: "4096Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
</code></pre>

**Comment by zhangxingdeppon** [comment]
> Cr = Custom Ressource, the yaml file you used to create your cluster. Thanks.
And I want to know other problem’s answer
How do I delete  rook-ceph-osd-prepare？for example rook-ceph-osd-prepare-d21112u04-61-142-kdzvl.
I have tryed to delete the job "rook-ceph-osd-prepare-d21112u04-61-142" , the cm "rook-ceph-osd-d21112u04-61-142-status" ,
In addition ,I have already commented on the clsuter yaml file section. 
<pre><code>
###############################################
#    - name: "d21112u04-61-142"
#      directories: # specific directories to use for storage can be specified for each node
#      - path: "/data2/ceph-storage-dir"
#      - path: "/data3/ceph-storage-dir"
#      resources:
#        limits:
#          cpu: "2"
#          memory: "4096Mi"
#        requests:
#           cpu: "500m"
#          memory: "1024Mi"
 ###############################################
after that, I restart the pod "rook-ceph-operator-6d699c8b79-b6n9c". but  "rook-ceph-osd-prepare-d21112u04-61-142-kdzvl" still the same as before.
I think I need  more time to study rook,LOL,Thanks.
</code></pre>

Resources are shown below：
![image](https://user-images.githubusercontent.com/16789841/60708975-ea0e3100-9f41-11e9-9691-613ecccae3c7.png)
![image](https://user-images.githubusercontent.com/16789841/60709013-feeac480-9f41-11e9-861e-e3dcd6840138.png)

**Comment by leseb** [comment]
Are you actually using `Rook v0.9.0-190.g818bf38`, could you update to a more recent version?

**Comment by zhangxingdeppon** [comment]
> Are you actually using `Rook v0.9.0-190.g818bf38`, could you update to a more recent version?
yes, the version is rook: v0.9.0-190.g818bf38
<pre><code>
sh-4.2# rook version
 rook: v0.9.0-190.g818bf38
</code></pre>

**Comment by zhangxingdeppon** [comment]
Could you give me some ideas ?How do I operate it?
I can't find  more knownledge from internet document,I am bad at it，Thanks .

**Comment by leseb** [comment]
You might be hitting a bug that was resolved long ago, please see: https://rook.io/docs/rook/v1.0/ceph-upgrade.html

**Comment by zhangxingdeppon** [comment]
> You might be hitting a bug that was resolved long ago, please see: https://rook.io/docs/rook/v1.0/ceph-upgrade.html

ok，I have seen it,thank you  very much
I'm not sure if I have understood it,means if i want to resolve it,the only operation is to do the upgrade. in fact，because of production env，so it will take some time before we can upgrade it，if there are other ways to avoid it,and what is the condition triggered by the bug?
I am sorry that I have so many questions to ask.LOL，thanks.

**Comment by leseb** [comment]
Perhaps this rings a bell @travisn?

**Comment by travisn** [comment]
If this is the last line in the log, it seems the `ceph osd` command has hung.
```
2019-07-04 07:55:47.258790 I | exec: Running command: ceph osd create 800da16e-0a2f-4f96-bf7d-3893769d6caf --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/158193659
```
If you connect to the osd prepare pod, can you access the path for the osd?

But it really is a concern to run production on a non-supported release build as was already mentioned. Upgrades aren't technically supported if you're running a master build like this, but hopefully the upgrade will still work for you.

**Comment by zhangxingdeppon** [comment]
> If this is the last line in the log, it seems the `ceph osd` command has hung.
> 
> ```
> 2019-07-04 07:55:47.258790 I | exec: Running command: ceph osd create 800da16e-0a2f-4f96-bf7d-3893769d6caf --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/158193659
> ```
> 
> If you connect to the osd prepare pod, can you access the path for the osd?
> 
> But it really is a concern to run production on a non-supported release build as was already mentioned. Upgrades aren't technically supported if you're running a master build like this, but hopefully the upgrade will still work for you.
emm，yes，i can access the path and manually create files and folders，and if  `ceph osd` command has hung，It  maybe return to normal by restarting，but it still failed same as before，it's very strange；
in addition，the “map[ceph-storage-dir -1]” what's meaning about “-1”，I have a lot of doubts about it，I have seen the nomal  logs，uaually the number  is integer great than zero，the above questions are just discussion ，I think finally we should  make a plan upgrade it . Thanks
