### ISSUE TITLE
go panic when starting ceph on OpenShift

### ISSUE THREAD

**Issue by raffaelespazzoli** [rook/rook#3541]
* Bug Report

**Deviation from expected behavior:**
When I create a ceph cluster I get the following go panic:
here is the log:
```
I0730 03:42:42.277293       6 controller.go:818] Started provisioner controller ceph.rook.io/block_rook-ceph-operator-86d85f8d-kn7f2_0b97dd3c-b27c-11e9-a63b-0a580a810213!
2019-07-30 03:43:08.335671 I | op-cluster: Detected ceph image version: 14.2.2 nautilus
2019-07-30 03:43:08.335690 I | op-cluster: CephCluster rook-ceph status: Creating
2019-07-30 03:43:08.355944 I | op-mon: start running mons
E0730 03:43:08.358702       6 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mon/mon.go:290
/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mon/mon.go:179
/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/cluster.go:188
/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/cluster.go:161
/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/controller.go:299
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:405
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:293
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:287
/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/controller.go:276
/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/controller.go:114
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:195
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:367
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:436
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:436
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:150
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:124
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:124
/usr/local/go/src/runtime/asm_amd64.s:1333
```

This behavior is highly reproduceable.
Here is my recipee for deploying rook: https://github.com/raffaelespazzoli/openshift-enablement-exam/tree/master/misc4.0/rook
please let me know if doing something wrong.

I'm deploying on OCP 4.1.7 running on AWS.

**Comment by noahdesu** [comment]
looks like a bug in the code where c.clusterInfo can be set to nil, but notice the error condition is checked before that return pointer is dereferenced.

```
	// get the cluster info from secret
	c.clusterInfo, c.maxMonID, c.mapping, err = CreateOrLoadClusterInfo(c.context, c.Namespace, &c.ownerRef)
	c.clusterInfo.CephVersion = cephVersion

	if err != nil {
		return fmt.Errorf("failed to get cluster info. %+v", err)
	}
```

**Comment by noahdesu** [comment]
@raffaelespazzoli looks like this has been fixed in master branch via https://github.com/rook/rook/commit/2ce2382676400f7afea591efd80b1ea4d43100d4#diff-8dabbe87d9ef76d84c1a4c06db5adfc2. Are you able to run master? @travisn should this be back ported?

**Comment by raffaelespazzoli** [comment]
@noahdesu how do I run master? can set latest in the image tag of the helm chart?

**Comment by travisn** [comment]
@raffaelespazzoli I'm surprised you would be seeing this in a new cluster. Can you check if you have cleaned up the cluster from a previous cluster? See the [cleanup steps](https://rook.io/docs/rook/v1.0/ceph-teardown.html). The only reason this should fail is if the metadata is in an expected state. In that case, running a master build might get past this error, but run into another error down the line. But for future reference you can test the master helm chart as seen [here](https://rook.io/docs/rook/v1.0/helm-operator.html#master).

@noahdesu Assuming we can find a workaround, I'd like to avoid a new 1.0 build so we can focus on 1.1.

**Comment by noahdesu** [comment]
It looks to me like CreateOrLoadClusterInfo could fail for a wide variety of reasons including failing to run some ceph CLI commands.

**Comment by raffaelespazzoli** [comment]
@travisn I cleaned up the nodes and deleted all the ceph related resource, but I can still reproduce the error.

**Comment by noahdesu** [comment]
@raffaelespazzoli are you able to test with master?

**Comment by raffaelespazzoli** [comment]
@noahdesu I tested with master, got the same error.
One weird thing: the latest chart version on the master repo is v1.0.0, I was using v1.0.4 from the official chart repo...

**Comment by noahdesu** [comment]
could you post the full operator log output running with master when it hits the error?

**Comment by raffaelespazzoli** [comment]
using the master tag for the image I was able to pass that error, now I see the following:
on daemonset/rook-ceph-agent
```
Error creating: pods "rook-ceph-agent-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used]
```
on daemonset rook-discover
```
Error creating: pods "rook-discover-" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
```
on job/rook-ceph-detect-version
```
Error creating: pods "rook-ceph-detect-version-" is forbidden: error looking up service account rook-ceph/rook-ceph-cmd-reporter: serviceaccount "rook-ceph-cmd-reporter" not found
```

I am running with the option: `ROOK_HOSTPATH_REQUIRES_PRIVILEGED=true`

so it looks that the wya I installed rook misses a bunch of stuff.
if it helps I am running helm in a tillerless way as this:
`helm template --namespace rook-ceph rook-ceph-v1.0.4.tgz | oc apply -f - -n rook-ceph`
so it openshift is detected by the chart via capabilities that could explain the issue. Is there a way to pass a variable to set openshift as the execution environment?

**Comment by raffaelespazzoli** [comment]
I fixed most of the issues. A couple of questions: 
1. what role should the rook-ceph-cmd-reporter service account have?
2. how can I make sure that the whole rook eco system run on specific nodes? nodeSelectors do not seems to be available for the daemonsets...

**Comment by raffaelespazzoli** [comment]
found the permissions for the `rook-ceph-cmd-reporter ` service account, they are not in the helm chart.
now the `rook-ceph-detect-version` job starts, but the job does not complete. the `init-copy-binaries` init container dies. It dies so fast that I am not able to capture the logs

**Comment by travisn** [comment]
It looks like #3369 added the permissions for the cmd-reporter to the helm chart. Which ones were missing? @BlaineEXE could you take a look?

**Comment by BlaineEXE** [comment]
I added the serviceaccount, role, and rolebinding necessary. I was confused at the time IIRC about why a lot of the resources didn't have namespaces associated with them, but I followed the existing trend. So it could be an issue with the namespaces in the chart. That's my first guess.
