### ISSUE TITLE
FailedMount rbd image is still being used

### ISSUE THREAD

**Issue by eroji** [rook/rook#4772]
I have a K8s cluster running Rook 1.2.2 with Ceph storage on 4 worker nodes. There was a network event that caused one of the nodes to disconnect. Now, I have a pod with PVC/PV that it cannot mount back successfully.

![image](https://user-images.githubusercontent.com/13228540/73392838-6de98b00-428f-11ea-80f3-0c0b12242a0f.png)

I looked around for help on how to solve this and it appears that I need to forcefully unmap the block image (correct me if I'm wrong), however I cannot figure out what the proper command is to do the unmap.

```
[root@rook-ceph-tools-796bc74d-knnrq /]# ceph -v
ceph version 14.2.6 (f0aa067ac7a02ee46ea48aa26c6e298b5ea272e9) nautilus (stable)
[root@rook-ceph-tools-796bc74d-knnrq /]# rbd device list
id pool        namespace image                                        snap device    
0  replicapool           csi-vol-3b1e48f6-dd7b-11e9-a3ac-de169c0427e5 -    /dev/rbd0 
1  replicapool           csi-vol-b55a421f-42c4-11ea-9ad0-eebbcbd9d910 -    /dev/rbd1 
[root@rook-ceph-tools-796bc74d-knnrq /]# rbd ls replicapool
csi-vol-0766a40c-d9a7-11e9-b460-e25a0dca5675
csi-vol-09aa92a0-d9a7-11e9-b460-e25a0dca5675
csi-vol-3b1bdf7d-dd7b-11e9-a3ac-de169c0427e5
csi-vol-3b1e48f6-dd7b-11e9-a3ac-de169c0427e5
csi-vol-3b470bad-dd7b-11e9-a3ac-de169c0427e5
csi-vol-3b488cc7-dd7b-11e9-a3ac-de169c0427e5
csi-vol-3d7a3f9a-dd7b-11e9-a3ac-de169c0427e5
csi-vol-b55a421f-42c4-11ea-9ad0-eebbcbd9d910
[root@rook-ceph-tools-796bc74d-knnrq /]# rbd unmap -o force /dev/rbd0/replicapool/csi-vol-3b1bdf7d-dd7b-11e9-a3ac-de169c0427e5
rbd: '/dev/rbd0/replicapool/csi-vol-3b1bdf7d-dd7b-11e9-a3ac-de169c0427e5' is not a block device
rbd: unmap failed: (22) Invalid argument
[root@rook-ceph-tools-796bc74d-knnrq /]# rbd unmap -o force /dev/rbd1/replicapool/csi-vol-3b1bdf7d-dd7b-11e9-a3ac-de169c0427e5 
rbd: '/dev/rbd1/replicapool/csi-vol-3b1bdf7d-dd7b-11e9-a3ac-de169c0427e5' is not a block device
rbd: unmap failed: (22) Invalid argument
[root@rook-ceph-tools-796bc74d-knnrq /]# rbd unmap -o force /dev/rbd1/csi-vol-3b1bdf7d-dd7b-11e9-a3ac-de169c0427e5            
rbd: '/dev/rbd1/csi-vol-3b1bdf7d-dd7b-11e9-a3ac-de169c0427e5' is not a block device
rbd: unmap failed: (22) Invalid argument
[root@rook-ceph-tools-796bc74d-knnrq /]# rbd unmap -o force /dev/rbd0/csi-vol-3b1bdf7d-dd7b-11e9-a3ac-de169c0427e5 
rbd: '/dev/rbd0/csi-vol-3b1bdf7d-dd7b-11e9-a3ac-de169c0427e5' is not a block device
rbd: unmap failed: (22) Invalid argument
```

**Comment by Madhu-1** [comment]
@eroji you need to unmap from the node where is it mapped not from the toolbox pod

**Comment by eroji** [comment]
@Madhu-1 how exactly do I unmap it?

**Comment by lipore** [comment]
You can search rbd image on all machines with the following command, if you are using rbdplugin.
`for pod in `kubectl -n rook-ceph get pods|grep rbdplugin|grep -v provisioner|awk '{print $1}'`                                                                                                                          
do
echo $pod
kubede exec -it -n rook-ceph $pod -c  csi-rbdplugin rbd -- device list
done`

**Comment by voarsh2** [comment]
> ```shell
> for pod in `kubectl -n rook-ceph get pods|grep rbdplugin|grep -v provisioner|awk '{print $1}'`                                                                                                                          
> do
> echo $pod
> kubede exec -it -n rook-ceph $pod -c  csi-rbdplugin rbd -- device list
> done
> ```

I've ran into this problem too - this cmd isn't working -  Any pointers?

**Comment by craslaw** [comment]
Typo in `kubede`. It should be `kubectl`.

```
for pod in `kubectl -n rook-ceph get pods|grep rbdplugin|grep -v provisioner|awk '{print $1}'`                                                                                                                        do echo $pod
kubectl exec -it -n rook-ceph $pod -c  csi-rbdplugin rbd -- device list
done
```

**Comment by suseether** [comment]
i am facing similar issue. but while i run rbd umap command from the pod where rbdplugin is running i still get the below error

rbd: '/dev/rbd0/replicapool/csi-vol-525dda30-86ed-11eb-8ad0-02674f0df230' is not a block device
rbd: unmap failed: (22) Invalid argument

any help to identify the issue.

**Comment by Madhu-1** [comment]
> i am facing similar issue. but while i run rbd umap command from the pod where rbdplugin is running i still get the below error
> 
> rbd: '/dev/rbd0/replicapool/csi-vol-525dda30-86ed-11eb-8ad0-02674f0df230' is not a block device
> rbd: unmap failed: (22) Invalid argument
> 
> any help to identify the issue.

The command is wrong it should be either `/dev/rbd0` or `replicapool/csi-vol-525dda30-86ed-11eb-8ad0-02674f0df230` should be input for  rbd unmap command.

**Comment by jhoblitt** [comment]
The command to list devices should be:

```
for pod in `kubectl -n rook-ceph get pods|grep rbdplugin|grep -v provisioner|awk '{print $1}'`; do echo $pod; kubectl exec -it -n rook-ceph $pod -c csi-rbdplugin -- rbd device list; done
```

**Comment by MCOfficer** [comment]
> The command to list devices should be:
> 
> ```
> for pod in `kubectl -n rook-ceph get pods|grep rbdplugin|grep -v provisioner|awk '{print $1}'`; do echo $pod; kubectl exec -it -n rook-ceph $pod -c csi-rbdplugin -- rbd device list; done
> ```


In case you're stuck with powershell:
```powershell
foreach ($pod in kubectl -n rook-ceph get pods -o custom-columns=NAME:.metadata.name | Select-String rbdplugin | Select-String -NotMatch provisioner) {
  Write-Host $pod;
  kubectl exec -it -n rook-ceph $pod -c csi-rbdplugin -- rbd device list;
}
```

**Comment by taxilian** [comment]
Just as a data point, I ran that and none of the csi pods say they are using it

**Comment by jhoblitt** [comment]
@taxilian did you take a look at #8322 ?

**Comment by taxilian** [comment]
I meant to come check back; somehow I missed it, it was actually listed on those but I didn't find it until I dug around and figured out how to check what watchers it had. Then circled back and found that somehow I must have been searching for the wrong name. At any rate, I don't know why kubernetes didn't release it but I had to manually unmount and unmap it and then it started working.
