### ISSUE TITLE
csi-provisioner crashes with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mkhpalm** [rook/rook#8128]
**Is this a bug report or feature request?**
* Bug Report

**Problem:**

Randomly throughout a day the leading csi-provisioner pod crashes with a nil pointer dereference on a cluster with lots of volumes. There are 8551 total in the cluster but only 22 of those are ceph volumes. 

Similar sounding ticket: https://github.com/kubernetes-csi/external-provisioner/issues/582

**Expected behavior:**

Acting leader csi-provisioner pod not to crash

**How to reproduce it (minimal and precise):**

Unsure but I think just having a lot of volumes in the cluster will cause it. It only seems to show up for us in larger clusters.

**File(s) to submit**:

```bash
I0613 19:07:07.406975       1 csi-provisioner.go:121] Version: v2.0.4-0-g0b9348770
I0613 19:07:07.407098       1 csi-provisioner.go:135] Building kube configs for running in cluster...
I0613 19:07:07.422046       1 connection.go:153] Connecting to unix:///csi/csi-provisioner.sock
I0613 19:07:07.422704       1 common.go:111] Probing CSI driver for readiness
W0613 19:07:07.426181       1 metrics.go:333] metrics endpoint will not be started because `metrics-address` was not specified.
I0613 19:07:07.427758       1 csi-provisioner.go:210] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I0613 19:07:07.429658       1 leaderelection.go:243] attempting to acquire leader lease  rook-ceph/rook-ceph-cephfs-csi-ceph-com...
I0613 19:07:07.440916       1 leaderelection.go:253] successfully acquired lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I0613 19:07:07.741463       1 controller.go:820] Starting provisioner controller rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-5c77db96f5-88l8f_e3d38e6f-d515-41e6-ac8c-9b71eded2132!
I0613 19:07:07.741521       1 clone_controller.go:66] Starting CloningProtection controller
I0613 19:07:07.741530       1 volume_store.go:97] Starting save volume queue
I0613 19:07:07.750406       1 clone_controller.go:84] Started CloningProtection controller
I0613 19:07:08.542567       1 controller.go:869] Started provisioner controller rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-5c77db96f5-88l8f_e3d38e6f-d515-41e6-ac8c-9b71eded2132!
E0613 20:22:07.723078       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 20:22:07.723099       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 20:37:08.033996       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 20:37:08.044631       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 20:52:08.036934       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 20:52:08.043814       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 20:52:08.045168       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 21:22:07.767930       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 21:22:08.063227       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 21:37:08.076996       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 21:37:08.088475       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 21:52:08.074251       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 22:07:08.093536       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 22:22:08.095421       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 22:52:07.852336       1 shared_informer.go:781] unrecognized notification: <nil>
E0613 23:37:07.884800       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 60 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x16ad960, 0x24bace0)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x16ad960, 0x24bace0)
	/home/travis/.gimme/versions/go1.15.linux.amd64/src/runtime/panic.go:969 +0x175
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:774 +0x194
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000574760)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000514f60, 0x1a7ee60, 0xc0004a0000, 0x167a201, 0xc00049e000)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000574760, 0x3b9aca00, 0x0, 0x1, 0xc00049e000)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000550900)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002b4a70, 0xc00056cea0)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x136ce54]

goroutine 60 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x16ad960, 0x24bace0)
	/home/travis/.gimme/versions/go1.15.linux.amd64/src/runtime/panic.go:969 +0x175
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:774 +0x194
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000574760)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000514f60, 0x1a7ee60, 0xc0004a0000, 0x167a201, 0xc00049e000)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000574760, 0x3b9aca00, 0x0, 0x1, 0xc00049e000)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000550900)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002b4a70, 0xc00056cea0)
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/travis/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
```

**Environment**:
* OS: Ubuntu Bionic 18.04 LTS
* Rook version: v1.5.11
* Storage backend version: ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)
* Kubernetes version: v1.20.7
* Kubernetes cluster type: kubeadm
* Storage backend status: HEALTH_OK
* CSI: Using defaults, e.g: https://github.com/rook/rook/blob/v1.5.11/pkg/operator/ceph/csi/spec.go#L106-L114

**Comment by mkhpalm** [comment]
I see the csi versions were already bumped in a PR: https://github.com/rook/rook/pull/8125

**Comment by travisn** [comment]
@mkhpalm Yes looks like the updated csi versions should fix the issue. Could you update the csi versions in your cluster and confirm? No need to wait for this in a rook release.

**Comment by mkhpalm** [comment]
I tried updating everything to match the above PR but the operator seems to have some issue detecting the ceph-csi version:

```bash
2021-06-15 19:13:57.149766 I | ceph-csi: Detected ceph CSI image version: "v3.3.1"
2021-06-15 19:13:57.149861 E | ceph-csi: invalid csi version. ceph CSI image needs to be at least version "v2.0.0"
github.com/rook/rook/pkg/operator/ceph/csi.validateCSIVersion
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/csi/spec.go:718
github.com/rook/rook/pkg/operator/ceph/csi.ValidateAndConfigureDrivers
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/csi/csi.go:35
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
```

Should I just be trying to update the kubernetes-csi images?

**Comment by travisn** [comment]
Oh I see you're on Rook v1.5, which didn't get support for v3.3. For the cephcsi image try `v3.2.2`

**Comment by mkhpalm** [comment]
I've run some tests and updated a large cluster using the following versions.

- cephcsi: v3.2.2
- csi-provisioner:v2.2.2
- csi-snapshotter:v4.1.1
- csi-attacher:v3.2.1
- csi-resizer:v1.2.0

 It may take a day or so to be sure if it resolves the crash but I'll report back regardless.

**Comment by mkhpalm** [comment]
Seems it still shows up with the latest csi-provisioner version v2.2.2:

```bash
...
E0617 20:05:17.031620       1 shared_informer.go:781] unrecognized notification: <nil>
E0617 20:20:17.017328       1 shared_informer.go:781] unrecognized notification: <nil>
E0617 20:35:17.022517       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 213 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19763a0, 0x298b4f0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x19763a0, 0x298b4f0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:774 +0x194
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000165f60)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a4cf60, 0x1de1ea0, 0xc002821920, 0x1932b01, 0xc000248360)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000165f60, 0x3b9aca00, 0x0, 0x1, 0xc000248360)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0004f8080)
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0003adf70, 0xc00217ef30)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x15d91f4]

goroutine 213 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x19763a0, 0x298b4f0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:774 +0x194
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000165f60)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a4cf60, 0x1de1ea0, 0xc002821920, 0x1932b01, 0xc000248360)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000165f60, 0x3b9aca00, 0x0, 0x1, 0xc000248360)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0004f8080)
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0003adf70, 0xc00217ef30)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
```

**Comment by travisn** [comment]
@Madhu-1 @Rakshith-R Any ideas on this one? Seems like we need to report an issue in the k8s provisioner.

**Comment by Madhu-1** [comment]
@travisn yes this need to be reported at external-provisioner repo

**Comment by mkhpalm** [comment]
I've mentioned it to them in what looks like a related ticket
